/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FlywaySchemaHistory;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiers;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Versions;
import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;

/** A class modelling indexes of tables of the <code>public</code> schema. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Indexes {

  // -------------------------------------------------------------------------
  // INDEX definitions
  // -------------------------------------------------------------------------

  public static final Index FLYWAY_SCHEMA_HISTORY_S_IDX = Indexes0.FLYWAY_SCHEMA_HISTORY_S_IDX;
  public static final Index IDX_IDENTIFIERS_UNIQ = Indexes0.IDX_IDENTIFIERS_UNIQ;
  public static final Index IDX_VERSIONS_INSTANCE_KEY = Indexes0.IDX_VERSIONS_INSTANCE_KEY;
  public static final Index IDX_VERSIONS_INSTANCE_VERSION_KEY =
      Indexes0.IDX_VERSIONS_INSTANCE_VERSION_KEY;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Indexes0 {
    public static Index FLYWAY_SCHEMA_HISTORY_S_IDX =
        Internal.createIndex(
            "flyway_schema_history_s_idx",
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            new OrderField[] {FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.SUCCESS},
            false);
    public static Index IDX_IDENTIFIERS_UNIQ =
        Internal.createIndex(
            "idx_identifiers_uniq",
            Identifiers.IDENTIFIERS,
            new OrderField[] {
              Identifiers.IDENTIFIERS.IDENTIFIABLE,
              Identifiers.IDENTIFIERS.NAMESPACE,
              Identifiers.IDENTIFIERS.IDENTIFIER
            },
            true);
    public static Index IDX_VERSIONS_INSTANCE_KEY =
        Internal.createIndex(
            "idx_versions_instance_key",
            Versions.VERSIONS,
            new OrderField[] {Versions.VERSIONS.INSTANCE_KEY},
            false);
    public static Index IDX_VERSIONS_INSTANCE_VERSION_KEY =
        Internal.createIndex(
            "idx_versions_instance_version_key",
            Versions.VERSIONS,
            new OrderField[] {Versions.VERSIONS.INSTANCE_VERSION_KEY},
            true);
  }
}
