/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ArticleCreators;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Articles;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.CollectionCollections;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.CollectionDigitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Collections;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Corporatebodies;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.DigitalobjectFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Digitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Entities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Fileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesAudio;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesImage;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesVideo;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FlywaySchemaHistory;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Geolocations;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Humansettlements;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiables;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiers;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiertypes;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ItemDigitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ItemWorks;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Items;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.PersistentLogins;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Persons;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Predicates;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ProjectDigitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Projects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntityEntities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntityFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntitypartEntities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntitypartFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RenderingTemplates;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicEntities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicSubtopics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Subtopics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.TopicSubtopics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Topics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Users;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Versions;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WebpageWebpages;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Webpages;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WebsiteWebpages;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Websites;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WorkCreators;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Works;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ArticleCreatorsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ArticlesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.CollectionCollectionsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.CollectionDigitalobjectsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.CollectionsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.CorporatebodiesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.DigitalobjectFileresourcesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.DigitalobjectsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.EntitiesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FileresourcesAudioRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FileresourcesImageRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FileresourcesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FileresourcesVideoRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FlywaySchemaHistoryRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.GeolocationsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.HumansettlementsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.IdentifiablesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.IdentifiersRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.IdentifiertypesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ItemDigitalobjectsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ItemWorksRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ItemsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.PersistentLoginsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.PersonsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.PredicatesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ProjectDigitalobjectsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ProjectsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.RelEntityEntitiesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.RelEntityFileresourcesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.RelEntitypartEntitiesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.RelEntitypartFileresourcesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.RenderingTemplatesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.SubtopicEntitiesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.SubtopicFileresourcesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.SubtopicSubtopicsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.SubtopicsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.TopicSubtopicsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.TopicsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.UsersRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.VersionsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WebpageWebpagesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WebpagesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WebsiteWebpagesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WebsitesRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WorkCreatorsRecord;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WorksRecord;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;

/**
 * A class modelling foreign key relationships and constraints of tables of the <code>public</code>
 * schema.
 */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

  // -------------------------------------------------------------------------
  // IDENTITY definitions
  // -------------------------------------------------------------------------

  public static final Identity<ArticlesRecord, Integer> IDENTITY_ARTICLES =
      Identities0.IDENTITY_ARTICLES;
  public static final Identity<CollectionsRecord, Integer> IDENTITY_COLLECTIONS =
      Identities0.IDENTITY_COLLECTIONS;
  public static final Identity<CorporatebodiesRecord, Integer> IDENTITY_CORPORATEBODIES =
      Identities0.IDENTITY_CORPORATEBODIES;
  public static final Identity<DigitalobjectsRecord, Integer> IDENTITY_DIGITALOBJECTS =
      Identities0.IDENTITY_DIGITALOBJECTS;
  public static final Identity<EntitiesRecord, Integer> IDENTITY_ENTITIES =
      Identities0.IDENTITY_ENTITIES;
  public static final Identity<GeolocationsRecord, Integer> IDENTITY_GEOLOCATIONS =
      Identities0.IDENTITY_GEOLOCATIONS;
  public static final Identity<HumansettlementsRecord, Integer> IDENTITY_HUMANSETTLEMENTS =
      Identities0.IDENTITY_HUMANSETTLEMENTS;
  public static final Identity<ItemsRecord, Integer> IDENTITY_ITEMS = Identities0.IDENTITY_ITEMS;
  public static final Identity<PersonsRecord, Integer> IDENTITY_PERSONS =
      Identities0.IDENTITY_PERSONS;
  public static final Identity<ProjectsRecord, Integer> IDENTITY_PROJECTS =
      Identities0.IDENTITY_PROJECTS;
  public static final Identity<TopicsRecord, Integer> IDENTITY_TOPICS = Identities0.IDENTITY_TOPICS;
  public static final Identity<UsersRecord, Integer> IDENTITY_USERS = Identities0.IDENTITY_USERS;
  public static final Identity<WebsitesRecord, Integer> IDENTITY_WEBSITES =
      Identities0.IDENTITY_WEBSITES;
  public static final Identity<WorksRecord, Integer> IDENTITY_WORKS = Identities0.IDENTITY_WORKS;

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<ArticleCreatorsRecord> ARTICLE_CREATORS_PKEY =
      UniqueKeys0.ARTICLE_CREATORS_PKEY;
  public static final UniqueKey<ArticlesRecord> NEW_ARTICLES_PKEY = UniqueKeys0.NEW_ARTICLES_PKEY;
  public static final UniqueKey<CollectionCollectionsRecord> COLLECTION_COLLECTIONS_PKEY =
      UniqueKeys0.COLLECTION_COLLECTIONS_PKEY;
  public static final UniqueKey<CollectionDigitalobjectsRecord> COLLECTION_DIGITALOBJECTS_PKEY =
      UniqueKeys0.COLLECTION_DIGITALOBJECTS_PKEY;
  public static final UniqueKey<CollectionsRecord> COLLECTIONS_UUID_KEY =
      UniqueKeys0.COLLECTIONS_UUID_KEY;
  public static final UniqueKey<CollectionsRecord> COLLECTIONS_PKEY = UniqueKeys0.COLLECTIONS_PKEY;
  public static final UniqueKey<CorporatebodiesRecord> CORPORATIONS_UUID_KEY =
      UniqueKeys0.CORPORATIONS_UUID_KEY;
  public static final UniqueKey<CorporatebodiesRecord> CORPORATIONS_PKEY =
      UniqueKeys0.CORPORATIONS_PKEY;
  public static final UniqueKey<DigitalobjectFileresourcesRecord>
      NEW_DIGITALOBJECT_FILERESOURCES_PKEY = UniqueKeys0.NEW_DIGITALOBJECT_FILERESOURCES_PKEY;
  public static final UniqueKey<DigitalobjectFileresourcesRecord>
      NEW_DIGITALOBJECT_FILERESOURCES_FILERESOURCE_UUID_KEY =
          UniqueKeys0.NEW_DIGITALOBJECT_FILERESOURCES_FILERESOURCE_UUID_KEY;
  public static final UniqueKey<DigitalobjectsRecord> NEW_DIGITALOBJECTS_PKEY =
      UniqueKeys0.NEW_DIGITALOBJECTS_PKEY;
  public static final UniqueKey<FileresourcesRecord> NEW_FILERESOURCES_PKEY =
      UniqueKeys0.NEW_FILERESOURCES_PKEY;
  public static final UniqueKey<FileresourcesAudioRecord> NEW_FILERESOURCES_AUDIO_PKEY =
      UniqueKeys0.NEW_FILERESOURCES_AUDIO_PKEY;
  public static final UniqueKey<FileresourcesImageRecord> NEW_FILERESOURCES_IMAGE_PKEY =
      UniqueKeys0.NEW_FILERESOURCES_IMAGE_PKEY;
  public static final UniqueKey<FileresourcesVideoRecord> NEW_FILERESOURCES_VIDEO_PKEY =
      UniqueKeys0.NEW_FILERESOURCES_VIDEO_PKEY;
  public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK =
      UniqueKeys0.FLYWAY_SCHEMA_HISTORY_PK;
  public static final UniqueKey<IdentifiablesRecord> NEW_IDENTIFIABLES_PKEY =
      UniqueKeys0.NEW_IDENTIFIABLES_PKEY;
  public static final UniqueKey<IdentifiersRecord> IDENTIFIERS_PKEY = UniqueKeys0.IDENTIFIERS_PKEY;
  public static final UniqueKey<IdentifiersRecord> UNIQUE_NAMESPACE_IDENTIFIER =
      UniqueKeys0.UNIQUE_NAMESPACE_IDENTIFIER;
  public static final UniqueKey<IdentifiertypesRecord> IDENTIFIERTYPES_NAMESPACE_KEY =
      UniqueKeys0.IDENTIFIERTYPES_NAMESPACE_KEY;
  public static final UniqueKey<IdentifiertypesRecord> IDENTIFIERTYPES_PKEY =
      UniqueKeys0.IDENTIFIERTYPES_PKEY;
  public static final UniqueKey<ItemDigitalobjectsRecord> ITEM_DIGITALOBJECTS_PKEY =
      UniqueKeys0.ITEM_DIGITALOBJECTS_PKEY;
  public static final UniqueKey<ItemWorksRecord> ITEM_WORKS_PKEY = UniqueKeys0.ITEM_WORKS_PKEY;
  public static final UniqueKey<PersistentLoginsRecord> PERSISTENT_LOGINS_PKEY =
      UniqueKeys0.PERSISTENT_LOGINS_PKEY;
  public static final UniqueKey<PredicatesRecord> PREDICATES_PKEY = UniqueKeys0.PREDICATES_PKEY;
  public static final UniqueKey<ProjectDigitalobjectsRecord> PROJECT_DIGITALOBJECTS_PKEY =
      UniqueKeys0.PROJECT_DIGITALOBJECTS_PKEY;
  public static final UniqueKey<ProjectsRecord> PROJECTS_UUID_KEY = UniqueKeys0.PROJECTS_UUID_KEY;
  public static final UniqueKey<ProjectsRecord> PROJECTS_PKEY = UniqueKeys0.PROJECTS_PKEY;
  public static final UniqueKey<RelEntityEntitiesRecord> REL_ENTITY_ENTITIES_PKEY =
      UniqueKeys0.REL_ENTITY_ENTITIES_PKEY;
  public static final UniqueKey<RelEntityFileresourcesRecord> REL_ENTITY_FILERESOURCES_PKEY =
      UniqueKeys0.REL_ENTITY_FILERESOURCES_PKEY;
  public static final UniqueKey<RelEntitypartEntitiesRecord> REL_ENTITYPART_ENTITIES_PKEY =
      UniqueKeys0.REL_ENTITYPART_ENTITIES_PKEY;
  public static final UniqueKey<RelEntitypartFileresourcesRecord>
      REL_ENTITYPART_FILERESOURCES_PKEY = UniqueKeys0.REL_ENTITYPART_FILERESOURCES_PKEY;
  public static final UniqueKey<RenderingTemplatesRecord> RENDERING_TEMPLATES_PKEY =
      UniqueKeys0.RENDERING_TEMPLATES_PKEY;
  public static final UniqueKey<SubtopicEntitiesRecord> SUBTOPIC_ENTITIES_PKEY =
      UniqueKeys0.SUBTOPIC_ENTITIES_PKEY;
  public static final UniqueKey<SubtopicFileresourcesRecord> SUBTOPIC_FILERESOURCES_PKEY =
      UniqueKeys0.SUBTOPIC_FILERESOURCES_PKEY;
  public static final UniqueKey<SubtopicSubtopicsRecord> SUBTOPIC_SUBTOPICS_PKEY =
      UniqueKeys0.SUBTOPIC_SUBTOPICS_PKEY;
  public static final UniqueKey<SubtopicsRecord> SUBTOPICS_PKEY = UniqueKeys0.SUBTOPICS_PKEY;
  public static final UniqueKey<TopicSubtopicsRecord> TOPIC_SUBTOPICS_PKEY =
      UniqueKeys0.TOPIC_SUBTOPICS_PKEY;
  public static final UniqueKey<TopicsRecord> TOPICS_PKEY = UniqueKeys0.TOPICS_PKEY;
  public static final UniqueKey<UsersRecord> USERS_PKEY = UniqueKeys0.USERS_PKEY;
  public static final UniqueKey<UsersRecord> USERS_UUID_KEY = UniqueKeys0.USERS_UUID_KEY;
  public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY = UniqueKeys0.USERS_EMAIL_KEY;
  public static final UniqueKey<VersionsRecord> VERSIONS_PKEY = UniqueKeys0.VERSIONS_PKEY;
  public static final UniqueKey<WebpageWebpagesRecord> NEW_WEBPAGE_WEBPAGES_PKEY =
      UniqueKeys0.NEW_WEBPAGE_WEBPAGES_PKEY;
  public static final UniqueKey<WebpageWebpagesRecord> NEW_WEBPAGE_WEBPAGES_CHILD_WEBPAGE_UUID_KEY =
      UniqueKeys0.NEW_WEBPAGE_WEBPAGES_CHILD_WEBPAGE_UUID_KEY;
  public static final UniqueKey<WebpagesRecord> NEW_WEBPAGES_PKEY = UniqueKeys0.NEW_WEBPAGES_PKEY;
  public static final UniqueKey<WebsiteWebpagesRecord> NEW_WEBSITE_WEBPAGES_PKEY =
      UniqueKeys0.NEW_WEBSITE_WEBPAGES_PKEY;
  public static final UniqueKey<WebsiteWebpagesRecord> NEW_WEBSITE_WEBPAGES_WEBPAGE_UUID_KEY =
      UniqueKeys0.NEW_WEBSITE_WEBPAGES_WEBPAGE_UUID_KEY;
  public static final UniqueKey<WebsitesRecord> NEW_WEBSITES_PKEY = UniqueKeys0.NEW_WEBSITES_PKEY;
  public static final UniqueKey<WebsitesRecord> NEW_WEBSITES_URL_KEY =
      UniqueKeys0.NEW_WEBSITES_URL_KEY;
  public static final UniqueKey<WorkCreatorsRecord> WORK_CREATORS_PKEY =
      UniqueKeys0.WORK_CREATORS_PKEY;

  // -------------------------------------------------------------------------
  // FOREIGN KEY definitions
  // -------------------------------------------------------------------------

  public static final ForeignKey<CollectionCollectionsRecord, CollectionsRecord>
      COLLECTION_COLLECTIONS__COLLECTION_COLLECTIONS_PARENT_COLLECTION_UUID_FKEY =
          ForeignKeys0.COLLECTION_COLLECTIONS__COLLECTION_COLLECTIONS_PARENT_COLLECTION_UUID_FKEY;
  public static final ForeignKey<CollectionCollectionsRecord, CollectionsRecord>
      COLLECTION_COLLECTIONS__COLLECTION_COLLECTIONS_CHILD_COLLECTION_UUID_FKEY =
          ForeignKeys0.COLLECTION_COLLECTIONS__COLLECTION_COLLECTIONS_CHILD_COLLECTION_UUID_FKEY;
  public static final ForeignKey<CollectionDigitalobjectsRecord, CollectionsRecord>
      COLLECTION_DIGITALOBJECTS__COLLECTION_DIGITALOBJECTS_COLLECTION_UUID_FKEY =
          ForeignKeys0.COLLECTION_DIGITALOBJECTS__COLLECTION_DIGITALOBJECTS_COLLECTION_UUID_FKEY;
  public static final ForeignKey<CollectionDigitalobjectsRecord, DigitalobjectsRecord>
      COLLECTION_DIGITALOBJECTS__COLLECTION_DIGITALOBJECTS_DIGITALOBJECT_UUID_FKEY =
          ForeignKeys0.COLLECTION_DIGITALOBJECTS__COLLECTION_DIGITALOBJECTS_DIGITALOBJECT_UUID_FKEY;
  public static final ForeignKey<DigitalobjectFileresourcesRecord, DigitalobjectsRecord>
      DIGITALOBJECT_FILERESOURCES__NEW_DIGITALOBJECT_FILERESOURCES_DIGITALOBJECT_UUID_FKEY =
          ForeignKeys0
              .DIGITALOBJECT_FILERESOURCES__NEW_DIGITALOBJECT_FILERESOURCES_DIGITALOBJECT_UUID_FKEY;
  public static final ForeignKey<ProjectDigitalobjectsRecord, ProjectsRecord>
      PROJECT_DIGITALOBJECTS__PROJECT_DIGITALOBJECTS_PROJECT_UUID_FKEY =
          ForeignKeys0.PROJECT_DIGITALOBJECTS__PROJECT_DIGITALOBJECTS_PROJECT_UUID_FKEY;
  public static final ForeignKey<ProjectDigitalobjectsRecord, DigitalobjectsRecord>
      PROJECT_DIGITALOBJECTS__PROJECT_DIGITALOBJECTS_DIGITALOBJECT_UUID_FKEY =
          ForeignKeys0.PROJECT_DIGITALOBJECTS__PROJECT_DIGITALOBJECTS_DIGITALOBJECT_UUID_FKEY;
  public static final ForeignKey<RelEntityEntitiesRecord, PredicatesRecord>
      REL_ENTITY_ENTITIES__FK_PREDICATE_PREDICATES =
          ForeignKeys0.REL_ENTITY_ENTITIES__FK_PREDICATE_PREDICATES;
  public static final ForeignKey<RelEntityFileresourcesRecord, FileresourcesRecord>
      REL_ENTITY_FILERESOURCES__REL_ENTITY_FILERESOURCES_FILERESOURCE_UUID_FKEY =
          ForeignKeys0.REL_ENTITY_FILERESOURCES__REL_ENTITY_FILERESOURCES_FILERESOURCE_UUID_FKEY;
  public static final ForeignKey<RelEntitypartFileresourcesRecord, FileresourcesRecord>
      REL_ENTITYPART_FILERESOURCES__REL_ENTITYPART_FILERESOURCES_FILERESOURCE_UUID_FKEY =
          ForeignKeys0
              .REL_ENTITYPART_FILERESOURCES__REL_ENTITYPART_FILERESOURCES_FILERESOURCE_UUID_FKEY;
  public static final ForeignKey<SubtopicEntitiesRecord, SubtopicsRecord>
      SUBTOPIC_ENTITIES__SUBTOPIC_ENTITIES_SUBTOPIC_UUID_FKEY =
          ForeignKeys0.SUBTOPIC_ENTITIES__SUBTOPIC_ENTITIES_SUBTOPIC_UUID_FKEY;
  public static final ForeignKey<SubtopicFileresourcesRecord, SubtopicsRecord>
      SUBTOPIC_FILERESOURCES__SUBTOPIC_FILERESOURCES_SUBTOPIC_UUID_FKEY =
          ForeignKeys0.SUBTOPIC_FILERESOURCES__SUBTOPIC_FILERESOURCES_SUBTOPIC_UUID_FKEY;
  public static final ForeignKey<SubtopicSubtopicsRecord, SubtopicsRecord>
      SUBTOPIC_SUBTOPICS__SUBTOPIC_SUBTOPICS_PARENT_SUBTOPIC_UUID_FKEY =
          ForeignKeys0.SUBTOPIC_SUBTOPICS__SUBTOPIC_SUBTOPICS_PARENT_SUBTOPIC_UUID_FKEY;
  public static final ForeignKey<SubtopicSubtopicsRecord, SubtopicsRecord>
      SUBTOPIC_SUBTOPICS__SUBTOPIC_SUBTOPICS_CHILD_SUBTOPIC_UUID_FKEY =
          ForeignKeys0.SUBTOPIC_SUBTOPICS__SUBTOPIC_SUBTOPICS_CHILD_SUBTOPIC_UUID_FKEY;
  public static final ForeignKey<TopicSubtopicsRecord, TopicsRecord>
      TOPIC_SUBTOPICS__TOPIC_SUBTOPICS_TOPIC_UUID_FKEY =
          ForeignKeys0.TOPIC_SUBTOPICS__TOPIC_SUBTOPICS_TOPIC_UUID_FKEY;
  public static final ForeignKey<TopicSubtopicsRecord, SubtopicsRecord>
      TOPIC_SUBTOPICS__TOPIC_SUBTOPICS_SUBTOPIC_UUID_FKEY =
          ForeignKeys0.TOPIC_SUBTOPICS__TOPIC_SUBTOPICS_SUBTOPIC_UUID_FKEY;
  public static final ForeignKey<WebpageWebpagesRecord, WebpagesRecord>
      WEBPAGE_WEBPAGES__NEW_WEBPAGE_WEBPAGES_PARENT_WEBPAGE_UUID_FKEY =
          ForeignKeys0.WEBPAGE_WEBPAGES__NEW_WEBPAGE_WEBPAGES_PARENT_WEBPAGE_UUID_FKEY;
  public static final ForeignKey<WebpageWebpagesRecord, WebpagesRecord>
      WEBPAGE_WEBPAGES__NEW_WEBPAGE_WEBPAGES_CHILD_WEBPAGE_UUID_FKEY =
          ForeignKeys0.WEBPAGE_WEBPAGES__NEW_WEBPAGE_WEBPAGES_CHILD_WEBPAGE_UUID_FKEY;
  public static final ForeignKey<WebsiteWebpagesRecord, WebsitesRecord>
      WEBSITE_WEBPAGES__NEW_WEBSITE_WEBPAGES_WEBSITE_UUID_FKEY =
          ForeignKeys0.WEBSITE_WEBPAGES__NEW_WEBSITE_WEBPAGES_WEBSITE_UUID_FKEY;
  public static final ForeignKey<WebsiteWebpagesRecord, WebpagesRecord>
      WEBSITE_WEBPAGES__NEW_WEBSITE_WEBPAGES_WEBPAGE_UUID_FKEY =
          ForeignKeys0.WEBSITE_WEBPAGES__NEW_WEBSITE_WEBPAGES_WEBPAGE_UUID_FKEY;

  // -------------------------------------------------------------------------
  // [#1459] distribute members to avoid static initialisers > 64kb
  // -------------------------------------------------------------------------

  private static class Identities0 {
    public static Identity<ArticlesRecord, Integer> IDENTITY_ARTICLES =
        Internal.createIdentity(Articles.ARTICLES, Articles.ARTICLES.REFID);
    public static Identity<CollectionsRecord, Integer> IDENTITY_COLLECTIONS =
        Internal.createIdentity(Collections.COLLECTIONS, Collections.COLLECTIONS.ID);
    public static Identity<CorporatebodiesRecord, Integer> IDENTITY_CORPORATEBODIES =
        Internal.createIdentity(
            Corporatebodies.CORPORATEBODIES, Corporatebodies.CORPORATEBODIES.ID);
    public static Identity<DigitalobjectsRecord, Integer> IDENTITY_DIGITALOBJECTS =
        Internal.createIdentity(Digitalobjects.DIGITALOBJECTS, Digitalobjects.DIGITALOBJECTS.REFID);
    public static Identity<EntitiesRecord, Integer> IDENTITY_ENTITIES =
        Internal.createIdentity(Entities.ENTITIES, Entities.ENTITIES.REFID);
    public static Identity<GeolocationsRecord, Integer> IDENTITY_GEOLOCATIONS =
        Internal.createIdentity(Geolocations.GEOLOCATIONS, Geolocations.GEOLOCATIONS.REFID);
    public static Identity<HumansettlementsRecord, Integer> IDENTITY_HUMANSETTLEMENTS =
        Internal.createIdentity(
            Humansettlements.HUMANSETTLEMENTS, Humansettlements.HUMANSETTLEMENTS.REFID);
    public static Identity<ItemsRecord, Integer> IDENTITY_ITEMS =
        Internal.createIdentity(Items.ITEMS, Items.ITEMS.REFID);
    public static Identity<PersonsRecord, Integer> IDENTITY_PERSONS =
        Internal.createIdentity(Persons.PERSONS, Persons.PERSONS.REFID);
    public static Identity<ProjectsRecord, Integer> IDENTITY_PROJECTS =
        Internal.createIdentity(Projects.PROJECTS, Projects.PROJECTS.ID);
    public static Identity<TopicsRecord, Integer> IDENTITY_TOPICS =
        Internal.createIdentity(Topics.TOPICS, Topics.TOPICS.REFID);
    public static Identity<UsersRecord, Integer> IDENTITY_USERS =
        Internal.createIdentity(Users.USERS, Users.USERS.ID);
    public static Identity<WebsitesRecord, Integer> IDENTITY_WEBSITES =
        Internal.createIdentity(Websites.WEBSITES, Websites.WEBSITES.REFID);
    public static Identity<WorksRecord, Integer> IDENTITY_WORKS =
        Internal.createIdentity(Works.WORKS, Works.WORKS.REFID);
  }

  private static class UniqueKeys0 {
    public static final UniqueKey<ArticleCreatorsRecord> ARTICLE_CREATORS_PKEY =
        Internal.createUniqueKey(
            ArticleCreators.ARTICLE_CREATORS,
            "article_creators_pkey",
            new TableField[] {
              ArticleCreators.ARTICLE_CREATORS.ARTICLE_UUID,
              ArticleCreators.ARTICLE_CREATORS.AGENT_UUID
            },
            true);
    public static final UniqueKey<ArticlesRecord> NEW_ARTICLES_PKEY =
        Internal.createUniqueKey(
            Articles.ARTICLES,
            "new_articles_pkey",
            new TableField[] {Articles.ARTICLES.UUID},
            true);
    public static final UniqueKey<CollectionCollectionsRecord> COLLECTION_COLLECTIONS_PKEY =
        Internal.createUniqueKey(
            CollectionCollections.COLLECTION_COLLECTIONS,
            "collection_collections_pkey",
            new TableField[] {
              CollectionCollections.COLLECTION_COLLECTIONS.PARENT_COLLECTION_UUID,
              CollectionCollections.COLLECTION_COLLECTIONS.CHILD_COLLECTION_UUID
            },
            true);
    public static final UniqueKey<CollectionDigitalobjectsRecord> COLLECTION_DIGITALOBJECTS_PKEY =
        Internal.createUniqueKey(
            CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS,
            "collection_digitalobjects_pkey",
            new TableField[] {
              CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS.COLLECTION_UUID,
              CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS.DIGITALOBJECT_UUID
            },
            true);
    public static final UniqueKey<CollectionsRecord> COLLECTIONS_UUID_KEY =
        Internal.createUniqueKey(
            Collections.COLLECTIONS,
            "collections_uuid_key",
            new TableField[] {Collections.COLLECTIONS.UUID},
            true);
    public static final UniqueKey<CollectionsRecord> COLLECTIONS_PKEY =
        Internal.createUniqueKey(
            Collections.COLLECTIONS,
            "collections_pkey",
            new TableField[] {Collections.COLLECTIONS.ID},
            true);
    public static final UniqueKey<CorporatebodiesRecord> CORPORATIONS_UUID_KEY =
        Internal.createUniqueKey(
            Corporatebodies.CORPORATEBODIES,
            "corporations_uuid_key",
            new TableField[] {Corporatebodies.CORPORATEBODIES.UUID},
            true);
    public static final UniqueKey<CorporatebodiesRecord> CORPORATIONS_PKEY =
        Internal.createUniqueKey(
            Corporatebodies.CORPORATEBODIES,
            "corporations_pkey",
            new TableField[] {Corporatebodies.CORPORATEBODIES.ID},
            true);
    public static final UniqueKey<DigitalobjectFileresourcesRecord>
        NEW_DIGITALOBJECT_FILERESOURCES_PKEY =
            Internal.createUniqueKey(
                DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES,
                "new_digitalobject_fileresources_pkey",
                new TableField[] {
                  DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.DIGITALOBJECT_UUID,
                  DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.FILERESOURCE_UUID
                },
                true);
    public static final UniqueKey<DigitalobjectFileresourcesRecord>
        NEW_DIGITALOBJECT_FILERESOURCES_FILERESOURCE_UUID_KEY =
            Internal.createUniqueKey(
                DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES,
                "new_digitalobject_fileresources_fileresource_uuid_key",
                new TableField[] {
                  DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.FILERESOURCE_UUID
                },
                true);
    public static final UniqueKey<DigitalobjectsRecord> NEW_DIGITALOBJECTS_PKEY =
        Internal.createUniqueKey(
            Digitalobjects.DIGITALOBJECTS,
            "new_digitalobjects_pkey",
            new TableField[] {Digitalobjects.DIGITALOBJECTS.UUID},
            true);
    public static final UniqueKey<FileresourcesRecord> NEW_FILERESOURCES_PKEY =
        Internal.createUniqueKey(
            Fileresources.FILERESOURCES,
            "new_fileresources_pkey",
            new TableField[] {Fileresources.FILERESOURCES.UUID},
            true);
    public static final UniqueKey<FileresourcesAudioRecord> NEW_FILERESOURCES_AUDIO_PKEY =
        Internal.createUniqueKey(
            FileresourcesAudio.FILERESOURCES_AUDIO,
            "new_fileresources_audio_pkey",
            new TableField[] {FileresourcesAudio.FILERESOURCES_AUDIO.UUID},
            true);
    public static final UniqueKey<FileresourcesImageRecord> NEW_FILERESOURCES_IMAGE_PKEY =
        Internal.createUniqueKey(
            FileresourcesImage.FILERESOURCES_IMAGE,
            "new_fileresources_image_pkey",
            new TableField[] {FileresourcesImage.FILERESOURCES_IMAGE.UUID},
            true);
    public static final UniqueKey<FileresourcesVideoRecord> NEW_FILERESOURCES_VIDEO_PKEY =
        Internal.createUniqueKey(
            FileresourcesVideo.FILERESOURCES_VIDEO,
            "new_fileresources_video_pkey",
            new TableField[] {FileresourcesVideo.FILERESOURCES_VIDEO.UUID},
            true);
    public static final UniqueKey<FlywaySchemaHistoryRecord> FLYWAY_SCHEMA_HISTORY_PK =
        Internal.createUniqueKey(
            FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY,
            "flyway_schema_history_pk",
            new TableField[] {FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY.INSTALLED_RANK},
            true);
    public static final UniqueKey<IdentifiablesRecord> NEW_IDENTIFIABLES_PKEY =
        Internal.createUniqueKey(
            Identifiables.IDENTIFIABLES,
            "new_identifiables_pkey",
            new TableField[] {Identifiables.IDENTIFIABLES.UUID},
            true);
    public static final UniqueKey<IdentifiersRecord> IDENTIFIERS_PKEY =
        Internal.createUniqueKey(
            Identifiers.IDENTIFIERS,
            "identifiers_pkey",
            new TableField[] {Identifiers.IDENTIFIERS.UUID},
            true);
    public static final UniqueKey<IdentifiersRecord> UNIQUE_NAMESPACE_IDENTIFIER =
        Internal.createUniqueKey(
            Identifiers.IDENTIFIERS,
            "unique_namespace_identifier",
            new TableField[] {
              Identifiers.IDENTIFIERS.NAMESPACE, Identifiers.IDENTIFIERS.IDENTIFIER
            },
            true);
    public static final UniqueKey<IdentifiertypesRecord> IDENTIFIERTYPES_NAMESPACE_KEY =
        Internal.createUniqueKey(
            Identifiertypes.IDENTIFIERTYPES,
            "identifiertypes_namespace_key",
            new TableField[] {Identifiertypes.IDENTIFIERTYPES.NAMESPACE},
            true);
    public static final UniqueKey<IdentifiertypesRecord> IDENTIFIERTYPES_PKEY =
        Internal.createUniqueKey(
            Identifiertypes.IDENTIFIERTYPES,
            "identifiertypes_pkey",
            new TableField[] {Identifiertypes.IDENTIFIERTYPES.UUID},
            true);
    public static final UniqueKey<ItemDigitalobjectsRecord> ITEM_DIGITALOBJECTS_PKEY =
        Internal.createUniqueKey(
            ItemDigitalobjects.ITEM_DIGITALOBJECTS,
            "item_digitalobjects_pkey",
            new TableField[] {
              ItemDigitalobjects.ITEM_DIGITALOBJECTS.ITEM_UUID,
              ItemDigitalobjects.ITEM_DIGITALOBJECTS.DIGITALOBJECT_UUID
            },
            true);
    public static final UniqueKey<ItemWorksRecord> ITEM_WORKS_PKEY =
        Internal.createUniqueKey(
            ItemWorks.ITEM_WORKS,
            "item_works_pkey",
            new TableField[] {ItemWorks.ITEM_WORKS.ITEM_UUID, ItemWorks.ITEM_WORKS.WORK_UUID},
            true);
    public static final UniqueKey<PersistentLoginsRecord> PERSISTENT_LOGINS_PKEY =
        Internal.createUniqueKey(
            PersistentLogins.PERSISTENT_LOGINS,
            "persistent_logins_pkey",
            new TableField[] {PersistentLogins.PERSISTENT_LOGINS.SERIES},
            true);
    public static final UniqueKey<PredicatesRecord> PREDICATES_PKEY =
        Internal.createUniqueKey(
            Predicates.PREDICATES,
            "predicates_pkey",
            new TableField[] {Predicates.PREDICATES.VALUE},
            true);
    public static final UniqueKey<ProjectDigitalobjectsRecord> PROJECT_DIGITALOBJECTS_PKEY =
        Internal.createUniqueKey(
            ProjectDigitalobjects.PROJECT_DIGITALOBJECTS,
            "project_digitalobjects_pkey",
            new TableField[] {
              ProjectDigitalobjects.PROJECT_DIGITALOBJECTS.PROJECT_UUID,
              ProjectDigitalobjects.PROJECT_DIGITALOBJECTS.DIGITALOBJECT_UUID
            },
            true);
    public static final UniqueKey<ProjectsRecord> PROJECTS_UUID_KEY =
        Internal.createUniqueKey(
            Projects.PROJECTS,
            "projects_uuid_key",
            new TableField[] {Projects.PROJECTS.UUID},
            true);
    public static final UniqueKey<ProjectsRecord> PROJECTS_PKEY =
        Internal.createUniqueKey(
            Projects.PROJECTS, "projects_pkey", new TableField[] {Projects.PROJECTS.ID}, true);
    public static final UniqueKey<RelEntityEntitiesRecord> REL_ENTITY_ENTITIES_PKEY =
        Internal.createUniqueKey(
            RelEntityEntities.REL_ENTITY_ENTITIES,
            "rel_entity_entities_pkey",
            new TableField[] {
              RelEntityEntities.REL_ENTITY_ENTITIES.SUBJECT_UUID,
              RelEntityEntities.REL_ENTITY_ENTITIES.PREDICATE,
              RelEntityEntities.REL_ENTITY_ENTITIES.OBJECT_UUID
            },
            true);
    public static final UniqueKey<RelEntityFileresourcesRecord> REL_ENTITY_FILERESOURCES_PKEY =
        Internal.createUniqueKey(
            RelEntityFileresources.REL_ENTITY_FILERESOURCES,
            "rel_entity_fileresources_pkey",
            new TableField[] {
              RelEntityFileresources.REL_ENTITY_FILERESOURCES.ENTITY_UUID,
              RelEntityFileresources.REL_ENTITY_FILERESOURCES.FILERESOURCE_UUID
            },
            true);
    public static final UniqueKey<RelEntitypartEntitiesRecord> REL_ENTITYPART_ENTITIES_PKEY =
        Internal.createUniqueKey(
            RelEntitypartEntities.REL_ENTITYPART_ENTITIES,
            "rel_entitypart_entities_pkey",
            new TableField[] {
              RelEntitypartEntities.REL_ENTITYPART_ENTITIES.ENTITYPART_UUID,
              RelEntitypartEntities.REL_ENTITYPART_ENTITIES.ENTITY_UUID
            },
            true);
    public static final UniqueKey<RelEntitypartFileresourcesRecord>
        REL_ENTITYPART_FILERESOURCES_PKEY =
            Internal.createUniqueKey(
                RelEntitypartFileresources.REL_ENTITYPART_FILERESOURCES,
                "rel_entitypart_fileresources_pkey",
                new TableField[] {
                  RelEntitypartFileresources.REL_ENTITYPART_FILERESOURCES.ENTITYPART_UUID,
                  RelEntitypartFileresources.REL_ENTITYPART_FILERESOURCES.FILERESOURCE_UUID
                },
                true);
    public static final UniqueKey<RenderingTemplatesRecord> RENDERING_TEMPLATES_PKEY =
        Internal.createUniqueKey(
            RenderingTemplates.RENDERING_TEMPLATES,
            "rendering_templates_pkey",
            new TableField[] {RenderingTemplates.RENDERING_TEMPLATES.UUID},
            true);
    public static final UniqueKey<SubtopicEntitiesRecord> SUBTOPIC_ENTITIES_PKEY =
        Internal.createUniqueKey(
            SubtopicEntities.SUBTOPIC_ENTITIES,
            "subtopic_entities_pkey",
            new TableField[] {
              SubtopicEntities.SUBTOPIC_ENTITIES.SUBTOPIC_UUID,
              SubtopicEntities.SUBTOPIC_ENTITIES.ENTITY_UUID
            },
            true);
    public static final UniqueKey<SubtopicFileresourcesRecord> SUBTOPIC_FILERESOURCES_PKEY =
        Internal.createUniqueKey(
            SubtopicFileresources.SUBTOPIC_FILERESOURCES,
            "subtopic_fileresources_pkey",
            new TableField[] {
              SubtopicFileresources.SUBTOPIC_FILERESOURCES.SUBTOPIC_UUID,
              SubtopicFileresources.SUBTOPIC_FILERESOURCES.FILERESOURCE_UUID
            },
            true);
    public static final UniqueKey<SubtopicSubtopicsRecord> SUBTOPIC_SUBTOPICS_PKEY =
        Internal.createUniqueKey(
            SubtopicSubtopics.SUBTOPIC_SUBTOPICS,
            "subtopic_subtopics_pkey",
            new TableField[] {
              SubtopicSubtopics.SUBTOPIC_SUBTOPICS.PARENT_SUBTOPIC_UUID,
              SubtopicSubtopics.SUBTOPIC_SUBTOPICS.CHILD_SUBTOPIC_UUID
            },
            true);
    public static final UniqueKey<SubtopicsRecord> SUBTOPICS_PKEY =
        Internal.createUniqueKey(
            Subtopics.SUBTOPICS,
            "subtopics_pkey",
            new TableField[] {Subtopics.SUBTOPICS.UUID},
            true);
    public static final UniqueKey<TopicSubtopicsRecord> TOPIC_SUBTOPICS_PKEY =
        Internal.createUniqueKey(
            TopicSubtopics.TOPIC_SUBTOPICS,
            "topic_subtopics_pkey",
            new TableField[] {
              TopicSubtopics.TOPIC_SUBTOPICS.TOPIC_UUID,
              TopicSubtopics.TOPIC_SUBTOPICS.SUBTOPIC_UUID
            },
            true);
    public static final UniqueKey<TopicsRecord> TOPICS_PKEY =
        Internal.createUniqueKey(
            Topics.TOPICS, "topics_pkey", new TableField[] {Topics.TOPICS.UUID}, true);
    public static final UniqueKey<UsersRecord> USERS_PKEY =
        Internal.createUniqueKey(
            Users.USERS, "users_pkey", new TableField[] {Users.USERS.ID}, true);
    public static final UniqueKey<UsersRecord> USERS_UUID_KEY =
        Internal.createUniqueKey(
            Users.USERS, "users_uuid_key", new TableField[] {Users.USERS.UUID}, true);
    public static final UniqueKey<UsersRecord> USERS_EMAIL_KEY =
        Internal.createUniqueKey(
            Users.USERS, "users_email_key", new TableField[] {Users.USERS.EMAIL}, true);
    public static final UniqueKey<VersionsRecord> VERSIONS_PKEY =
        Internal.createUniqueKey(
            Versions.VERSIONS, "versions_pkey", new TableField[] {Versions.VERSIONS.UUID}, true);
    public static final UniqueKey<WebpageWebpagesRecord> NEW_WEBPAGE_WEBPAGES_PKEY =
        Internal.createUniqueKey(
            WebpageWebpages.WEBPAGE_WEBPAGES,
            "new_webpage_webpages_pkey",
            new TableField[] {
              WebpageWebpages.WEBPAGE_WEBPAGES.PARENT_WEBPAGE_UUID,
              WebpageWebpages.WEBPAGE_WEBPAGES.CHILD_WEBPAGE_UUID
            },
            true);
    public static final UniqueKey<WebpageWebpagesRecord>
        NEW_WEBPAGE_WEBPAGES_CHILD_WEBPAGE_UUID_KEY =
            Internal.createUniqueKey(
                WebpageWebpages.WEBPAGE_WEBPAGES,
                "new_webpage_webpages_child_webpage_uuid_key",
                new TableField[] {WebpageWebpages.WEBPAGE_WEBPAGES.CHILD_WEBPAGE_UUID},
                true);
    public static final UniqueKey<WebpagesRecord> NEW_WEBPAGES_PKEY =
        Internal.createUniqueKey(
            Webpages.WEBPAGES,
            "new_webpages_pkey",
            new TableField[] {Webpages.WEBPAGES.UUID},
            true);
    public static final UniqueKey<WebsiteWebpagesRecord> NEW_WEBSITE_WEBPAGES_PKEY =
        Internal.createUniqueKey(
            WebsiteWebpages.WEBSITE_WEBPAGES,
            "new_website_webpages_pkey",
            new TableField[] {
              WebsiteWebpages.WEBSITE_WEBPAGES.WEBSITE_UUID,
              WebsiteWebpages.WEBSITE_WEBPAGES.WEBPAGE_UUID
            },
            true);
    public static final UniqueKey<WebsiteWebpagesRecord> NEW_WEBSITE_WEBPAGES_WEBPAGE_UUID_KEY =
        Internal.createUniqueKey(
            WebsiteWebpages.WEBSITE_WEBPAGES,
            "new_website_webpages_webpage_uuid_key",
            new TableField[] {WebsiteWebpages.WEBSITE_WEBPAGES.WEBPAGE_UUID},
            true);
    public static final UniqueKey<WebsitesRecord> NEW_WEBSITES_PKEY =
        Internal.createUniqueKey(
            Websites.WEBSITES,
            "new_websites_pkey",
            new TableField[] {Websites.WEBSITES.UUID},
            true);
    public static final UniqueKey<WebsitesRecord> NEW_WEBSITES_URL_KEY =
        Internal.createUniqueKey(
            Websites.WEBSITES,
            "new_websites_url_key",
            new TableField[] {Websites.WEBSITES.URL},
            true);
    public static final UniqueKey<WorkCreatorsRecord> WORK_CREATORS_PKEY =
        Internal.createUniqueKey(
            WorkCreators.WORK_CREATORS,
            "work_creators_pkey",
            new TableField[] {
              WorkCreators.WORK_CREATORS.WORK_UUID, WorkCreators.WORK_CREATORS.AGENT_UUID
            },
            true);
  }

  private static class ForeignKeys0 {
    public static final ForeignKey<CollectionCollectionsRecord, CollectionsRecord>
        COLLECTION_COLLECTIONS__COLLECTION_COLLECTIONS_PARENT_COLLECTION_UUID_FKEY =
            Internal.createForeignKey(
                Keys.COLLECTIONS_UUID_KEY,
                CollectionCollections.COLLECTION_COLLECTIONS,
                "collection_collections_parent_collection_uuid_fkey",
                new TableField[] {
                  CollectionCollections.COLLECTION_COLLECTIONS.PARENT_COLLECTION_UUID
                },
                true);
    public static final ForeignKey<CollectionCollectionsRecord, CollectionsRecord>
        COLLECTION_COLLECTIONS__COLLECTION_COLLECTIONS_CHILD_COLLECTION_UUID_FKEY =
            Internal.createForeignKey(
                Keys.COLLECTIONS_UUID_KEY,
                CollectionCollections.COLLECTION_COLLECTIONS,
                "collection_collections_child_collection_uuid_fkey",
                new TableField[] {
                  CollectionCollections.COLLECTION_COLLECTIONS.CHILD_COLLECTION_UUID
                },
                true);
    public static final ForeignKey<CollectionDigitalobjectsRecord, CollectionsRecord>
        COLLECTION_DIGITALOBJECTS__COLLECTION_DIGITALOBJECTS_COLLECTION_UUID_FKEY =
            Internal.createForeignKey(
                Keys.COLLECTIONS_UUID_KEY,
                CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS,
                "collection_digitalobjects_collection_uuid_fkey",
                new TableField[] {
                  CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS.COLLECTION_UUID
                },
                true);
    public static final ForeignKey<CollectionDigitalobjectsRecord, DigitalobjectsRecord>
        COLLECTION_DIGITALOBJECTS__COLLECTION_DIGITALOBJECTS_DIGITALOBJECT_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_DIGITALOBJECTS_PKEY,
                CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS,
                "collection_digitalobjects_digitalobject_uuid_fkey",
                new TableField[] {
                  CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS.DIGITALOBJECT_UUID
                },
                true);
    public static final ForeignKey<DigitalobjectFileresourcesRecord, DigitalobjectsRecord>
        DIGITALOBJECT_FILERESOURCES__NEW_DIGITALOBJECT_FILERESOURCES_DIGITALOBJECT_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_DIGITALOBJECTS_PKEY,
                DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES,
                "new_digitalobject_fileresources_digitalobject_uuid_fkey",
                new TableField[] {
                  DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.DIGITALOBJECT_UUID
                },
                true);
    public static final ForeignKey<ProjectDigitalobjectsRecord, ProjectsRecord>
        PROJECT_DIGITALOBJECTS__PROJECT_DIGITALOBJECTS_PROJECT_UUID_FKEY =
            Internal.createForeignKey(
                Keys.PROJECTS_UUID_KEY,
                ProjectDigitalobjects.PROJECT_DIGITALOBJECTS,
                "project_digitalobjects_project_uuid_fkey",
                new TableField[] {ProjectDigitalobjects.PROJECT_DIGITALOBJECTS.PROJECT_UUID},
                true);
    public static final ForeignKey<ProjectDigitalobjectsRecord, DigitalobjectsRecord>
        PROJECT_DIGITALOBJECTS__PROJECT_DIGITALOBJECTS_DIGITALOBJECT_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_DIGITALOBJECTS_PKEY,
                ProjectDigitalobjects.PROJECT_DIGITALOBJECTS,
                "project_digitalobjects_digitalobject_uuid_fkey",
                new TableField[] {ProjectDigitalobjects.PROJECT_DIGITALOBJECTS.DIGITALOBJECT_UUID},
                true);
    public static final ForeignKey<RelEntityEntitiesRecord, PredicatesRecord>
        REL_ENTITY_ENTITIES__FK_PREDICATE_PREDICATES =
            Internal.createForeignKey(
                Keys.PREDICATES_PKEY,
                RelEntityEntities.REL_ENTITY_ENTITIES,
                "fk_predicate_predicates",
                new TableField[] {RelEntityEntities.REL_ENTITY_ENTITIES.PREDICATE},
                true);
    public static final ForeignKey<RelEntityFileresourcesRecord, FileresourcesRecord>
        REL_ENTITY_FILERESOURCES__REL_ENTITY_FILERESOURCES_FILERESOURCE_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_FILERESOURCES_PKEY,
                RelEntityFileresources.REL_ENTITY_FILERESOURCES,
                "rel_entity_fileresources_fileresource_uuid_fkey",
                new TableField[] {
                  RelEntityFileresources.REL_ENTITY_FILERESOURCES.FILERESOURCE_UUID
                },
                true);
    public static final ForeignKey<RelEntitypartFileresourcesRecord, FileresourcesRecord>
        REL_ENTITYPART_FILERESOURCES__REL_ENTITYPART_FILERESOURCES_FILERESOURCE_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_FILERESOURCES_PKEY,
                RelEntitypartFileresources.REL_ENTITYPART_FILERESOURCES,
                "rel_entitypart_fileresources_fileresource_uuid_fkey",
                new TableField[] {
                  RelEntitypartFileresources.REL_ENTITYPART_FILERESOURCES.FILERESOURCE_UUID
                },
                true);
    public static final ForeignKey<SubtopicEntitiesRecord, SubtopicsRecord>
        SUBTOPIC_ENTITIES__SUBTOPIC_ENTITIES_SUBTOPIC_UUID_FKEY =
            Internal.createForeignKey(
                Keys.SUBTOPICS_PKEY,
                SubtopicEntities.SUBTOPIC_ENTITIES,
                "subtopic_entities_subtopic_uuid_fkey",
                new TableField[] {SubtopicEntities.SUBTOPIC_ENTITIES.SUBTOPIC_UUID},
                true);
    public static final ForeignKey<SubtopicFileresourcesRecord, SubtopicsRecord>
        SUBTOPIC_FILERESOURCES__SUBTOPIC_FILERESOURCES_SUBTOPIC_UUID_FKEY =
            Internal.createForeignKey(
                Keys.SUBTOPICS_PKEY,
                SubtopicFileresources.SUBTOPIC_FILERESOURCES,
                "subtopic_fileresources_subtopic_uuid_fkey",
                new TableField[] {SubtopicFileresources.SUBTOPIC_FILERESOURCES.SUBTOPIC_UUID},
                true);
    public static final ForeignKey<SubtopicSubtopicsRecord, SubtopicsRecord>
        SUBTOPIC_SUBTOPICS__SUBTOPIC_SUBTOPICS_PARENT_SUBTOPIC_UUID_FKEY =
            Internal.createForeignKey(
                Keys.SUBTOPICS_PKEY,
                SubtopicSubtopics.SUBTOPIC_SUBTOPICS,
                "subtopic_subtopics_parent_subtopic_uuid_fkey",
                new TableField[] {SubtopicSubtopics.SUBTOPIC_SUBTOPICS.PARENT_SUBTOPIC_UUID},
                true);
    public static final ForeignKey<SubtopicSubtopicsRecord, SubtopicsRecord>
        SUBTOPIC_SUBTOPICS__SUBTOPIC_SUBTOPICS_CHILD_SUBTOPIC_UUID_FKEY =
            Internal.createForeignKey(
                Keys.SUBTOPICS_PKEY,
                SubtopicSubtopics.SUBTOPIC_SUBTOPICS,
                "subtopic_subtopics_child_subtopic_uuid_fkey",
                new TableField[] {SubtopicSubtopics.SUBTOPIC_SUBTOPICS.CHILD_SUBTOPIC_UUID},
                true);
    public static final ForeignKey<TopicSubtopicsRecord, TopicsRecord>
        TOPIC_SUBTOPICS__TOPIC_SUBTOPICS_TOPIC_UUID_FKEY =
            Internal.createForeignKey(
                Keys.TOPICS_PKEY,
                TopicSubtopics.TOPIC_SUBTOPICS,
                "topic_subtopics_topic_uuid_fkey",
                new TableField[] {TopicSubtopics.TOPIC_SUBTOPICS.TOPIC_UUID},
                true);
    public static final ForeignKey<TopicSubtopicsRecord, SubtopicsRecord>
        TOPIC_SUBTOPICS__TOPIC_SUBTOPICS_SUBTOPIC_UUID_FKEY =
            Internal.createForeignKey(
                Keys.SUBTOPICS_PKEY,
                TopicSubtopics.TOPIC_SUBTOPICS,
                "topic_subtopics_subtopic_uuid_fkey",
                new TableField[] {TopicSubtopics.TOPIC_SUBTOPICS.SUBTOPIC_UUID},
                true);
    public static final ForeignKey<WebpageWebpagesRecord, WebpagesRecord>
        WEBPAGE_WEBPAGES__NEW_WEBPAGE_WEBPAGES_PARENT_WEBPAGE_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_WEBPAGES_PKEY,
                WebpageWebpages.WEBPAGE_WEBPAGES,
                "new_webpage_webpages_parent_webpage_uuid_fkey",
                new TableField[] {WebpageWebpages.WEBPAGE_WEBPAGES.PARENT_WEBPAGE_UUID},
                true);
    public static final ForeignKey<WebpageWebpagesRecord, WebpagesRecord>
        WEBPAGE_WEBPAGES__NEW_WEBPAGE_WEBPAGES_CHILD_WEBPAGE_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_WEBPAGES_PKEY,
                WebpageWebpages.WEBPAGE_WEBPAGES,
                "new_webpage_webpages_child_webpage_uuid_fkey",
                new TableField[] {WebpageWebpages.WEBPAGE_WEBPAGES.CHILD_WEBPAGE_UUID},
                true);
    public static final ForeignKey<WebsiteWebpagesRecord, WebsitesRecord>
        WEBSITE_WEBPAGES__NEW_WEBSITE_WEBPAGES_WEBSITE_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_WEBSITES_PKEY,
                WebsiteWebpages.WEBSITE_WEBPAGES,
                "new_website_webpages_website_uuid_fkey",
                new TableField[] {WebsiteWebpages.WEBSITE_WEBPAGES.WEBSITE_UUID},
                true);
    public static final ForeignKey<WebsiteWebpagesRecord, WebpagesRecord>
        WEBSITE_WEBPAGES__NEW_WEBSITE_WEBPAGES_WEBPAGE_UUID_FKEY =
            Internal.createForeignKey(
                Keys.NEW_WEBPAGES_PKEY,
                WebsiteWebpages.WEBSITE_WEBPAGES,
                "new_website_webpages_webpage_uuid_fkey",
                new TableField[] {WebsiteWebpages.WEBSITE_WEBPAGES.WEBPAGE_UUID},
                true);
  }
}
