/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db;

import org.jooq.Sequence;
import org.jooq.impl.Internal;

/** Convenience access to all sequences in public */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Sequences {

  /** The sequence <code>public.collections_id_seq</code> */
  public static final Sequence<Integer> COLLECTIONS_ID_SEQ =
      Internal.createSequence(
          "collections_id_seq",
          Public.PUBLIC,
          org.jooq.impl.SQLDataType.INTEGER.nullable(false),
          null,
          null,
          null,
          null,
          false,
          null);

  /** The sequence <code>public.corporations_id_seq</code> */
  public static final Sequence<Integer> CORPORATIONS_ID_SEQ =
      Internal.createSequence(
          "corporations_id_seq",
          Public.PUBLIC,
          org.jooq.impl.SQLDataType.INTEGER.nullable(false),
          null,
          null,
          null,
          null,
          false,
          null);

  /** The sequence <code>public.entities_refid_seq</code> */
  public static final Sequence<Integer> ENTITIES_REFID_SEQ =
      Internal.createSequence(
          "entities_refid_seq",
          Public.PUBLIC,
          org.jooq.impl.SQLDataType.INTEGER.nullable(false),
          null,
          null,
          null,
          null,
          false,
          null);

  /** The sequence <code>public.projects_id_seq</code> */
  public static final Sequence<Integer> PROJECTS_ID_SEQ =
      Internal.createSequence(
          "projects_id_seq",
          Public.PUBLIC,
          org.jooq.impl.SQLDataType.INTEGER.nullable(false),
          null,
          null,
          null,
          null,
          false,
          null);

  /** The sequence <code>public.users_id_seq</code> */
  public static final Sequence<Integer> USERS_ID_SEQ =
      Internal.createSequence(
          "users_id_seq",
          Public.PUBLIC,
          org.jooq.impl.SQLDataType.INTEGER.nullable(false),
          null,
          null,
          null,
          null,
          false,
          null);
}
