/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ArticleCreators;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Articles;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.CollectionCollections;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.CollectionDigitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Collections;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Corporatebodies;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.DigitalobjectFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Digitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Entities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Fileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesApplication;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesAudio;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesImage;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesLinkeddata;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesText;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FileresourcesVideo;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.FlywaySchemaHistory;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Geolocations;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Humansettlements;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiables;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiers;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Identifiertypes;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ItemDigitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ItemWorks;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Items;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.PersistentLogins;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Persons;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Predicates;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ProjectDigitalobjects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Projects;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntityEntities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntityFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntitypartEntities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RelEntitypartFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.RenderingTemplates;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicEntities;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicFileresources;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicSubtopics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Subtopics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.TopicSubtopics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Topics;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Users;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Versions;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WebpageWebpages;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Webpages;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WebsiteWebpages;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Websites;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WorkCreators;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Works;

/** Convenience access to all tables in public */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

  /** The table <code>public.article_creators</code>. */
  public static final ArticleCreators ARTICLE_CREATORS = ArticleCreators.ARTICLE_CREATORS;

  /** The table <code>public.articles</code>. */
  public static final Articles ARTICLES = Articles.ARTICLES;

  /** The table <code>public.collection_collections</code>. */
  public static final CollectionCollections COLLECTION_COLLECTIONS =
      CollectionCollections.COLLECTION_COLLECTIONS;

  /** The table <code>public.collection_digitalobjects</code>. */
  public static final CollectionDigitalobjects COLLECTION_DIGITALOBJECTS =
      CollectionDigitalobjects.COLLECTION_DIGITALOBJECTS;

  /** The table <code>public.collections</code>. */
  public static final Collections COLLECTIONS = Collections.COLLECTIONS;

  /** The table <code>public.corporatebodies</code>. */
  public static final Corporatebodies CORPORATEBODIES = Corporatebodies.CORPORATEBODIES;

  /** The table <code>public.digitalobject_fileresources</code>. */
  public static final DigitalobjectFileresources DIGITALOBJECT_FILERESOURCES =
      DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES;

  /** The table <code>public.digitalobjects</code>. */
  public static final Digitalobjects DIGITALOBJECTS = Digitalobjects.DIGITALOBJECTS;

  /** The table <code>public.entities</code>. */
  public static final Entities ENTITIES = Entities.ENTITIES;

  /** The table <code>public.fileresources</code>. */
  public static final Fileresources FILERESOURCES = Fileresources.FILERESOURCES;

  /** The table <code>public.fileresources_application</code>. */
  public static final FileresourcesApplication FILERESOURCES_APPLICATION =
      FileresourcesApplication.FILERESOURCES_APPLICATION;

  /** The table <code>public.fileresources_audio</code>. */
  public static final FileresourcesAudio FILERESOURCES_AUDIO =
      FileresourcesAudio.FILERESOURCES_AUDIO;

  /** The table <code>public.fileresources_image</code>. */
  public static final FileresourcesImage FILERESOURCES_IMAGE =
      FileresourcesImage.FILERESOURCES_IMAGE;

  /** The table <code>public.fileresources_linkeddata</code>. */
  public static final FileresourcesLinkeddata FILERESOURCES_LINKEDDATA =
      FileresourcesLinkeddata.FILERESOURCES_LINKEDDATA;

  /** The table <code>public.fileresources_text</code>. */
  public static final FileresourcesText FILERESOURCES_TEXT = FileresourcesText.FILERESOURCES_TEXT;

  /** The table <code>public.fileresources_video</code>. */
  public static final FileresourcesVideo FILERESOURCES_VIDEO =
      FileresourcesVideo.FILERESOURCES_VIDEO;

  /** The table <code>public.flyway_schema_history</code>. */
  public static final FlywaySchemaHistory FLYWAY_SCHEMA_HISTORY =
      FlywaySchemaHistory.FLYWAY_SCHEMA_HISTORY;

  /** The table <code>public.geolocations</code>. */
  public static final Geolocations GEOLOCATIONS = Geolocations.GEOLOCATIONS;

  /** The table <code>public.humansettlements</code>. */
  public static final Humansettlements HUMANSETTLEMENTS = Humansettlements.HUMANSETTLEMENTS;

  /** The table <code>public.identifiables</code>. */
  public static final Identifiables IDENTIFIABLES = Identifiables.IDENTIFIABLES;

  /** The table <code>public.identifiers</code>. */
  public static final Identifiers IDENTIFIERS = Identifiers.IDENTIFIERS;

  /** The table <code>public.identifiertypes</code>. */
  public static final Identifiertypes IDENTIFIERTYPES = Identifiertypes.IDENTIFIERTYPES;

  /** The table <code>public.item_digitalobjects</code>. */
  public static final ItemDigitalobjects ITEM_DIGITALOBJECTS =
      ItemDigitalobjects.ITEM_DIGITALOBJECTS;

  /** The table <code>public.item_works</code>. */
  public static final ItemWorks ITEM_WORKS = ItemWorks.ITEM_WORKS;

  /** The table <code>public.items</code>. */
  public static final Items ITEMS = Items.ITEMS;

  /** The table <code>public.persistent_logins</code>. */
  public static final PersistentLogins PERSISTENT_LOGINS = PersistentLogins.PERSISTENT_LOGINS;

  /** The table <code>public.persons</code>. */
  public static final Persons PERSONS = Persons.PERSONS;

  /** The table <code>public.predicates</code>. */
  public static final Predicates PREDICATES = Predicates.PREDICATES;

  /** The table <code>public.project_digitalobjects</code>. */
  public static final ProjectDigitalobjects PROJECT_DIGITALOBJECTS =
      ProjectDigitalobjects.PROJECT_DIGITALOBJECTS;

  /** The table <code>public.projects</code>. */
  public static final Projects PROJECTS = Projects.PROJECTS;

  /** The table <code>public.rel_entity_entities</code>. */
  public static final RelEntityEntities REL_ENTITY_ENTITIES = RelEntityEntities.REL_ENTITY_ENTITIES;

  /** The table <code>public.rel_entity_fileresources</code>. */
  public static final RelEntityFileresources REL_ENTITY_FILERESOURCES =
      RelEntityFileresources.REL_ENTITY_FILERESOURCES;

  /** The table <code>public.rel_entitypart_entities</code>. */
  public static final RelEntitypartEntities REL_ENTITYPART_ENTITIES =
      RelEntitypartEntities.REL_ENTITYPART_ENTITIES;

  /** The table <code>public.rel_entitypart_fileresources</code>. */
  public static final RelEntitypartFileresources REL_ENTITYPART_FILERESOURCES =
      RelEntitypartFileresources.REL_ENTITYPART_FILERESOURCES;

  /** The table <code>public.rendering_templates</code>. */
  public static final RenderingTemplates RENDERING_TEMPLATES =
      RenderingTemplates.RENDERING_TEMPLATES;

  /** The table <code>public.subtopic_entities</code>. */
  public static final SubtopicEntities SUBTOPIC_ENTITIES = SubtopicEntities.SUBTOPIC_ENTITIES;

  /** The table <code>public.subtopic_fileresources</code>. */
  public static final SubtopicFileresources SUBTOPIC_FILERESOURCES =
      SubtopicFileresources.SUBTOPIC_FILERESOURCES;

  /** The table <code>public.subtopic_subtopics</code>. */
  public static final SubtopicSubtopics SUBTOPIC_SUBTOPICS = SubtopicSubtopics.SUBTOPIC_SUBTOPICS;

  /** The table <code>public.subtopics</code>. */
  public static final Subtopics SUBTOPICS = Subtopics.SUBTOPICS;

  /** The table <code>public.topic_subtopics</code>. */
  public static final TopicSubtopics TOPIC_SUBTOPICS = TopicSubtopics.TOPIC_SUBTOPICS;

  /** The table <code>public.topics</code>. */
  public static final Topics TOPICS = Topics.TOPICS;

  /** The table <code>public.users</code>. */
  public static final Users USERS = Users.USERS;

  /** The table <code>public.versions</code>. */
  public static final Versions VERSIONS = Versions.VERSIONS;

  /** The table <code>public.webpage_webpages</code>. */
  public static final WebpageWebpages WEBPAGE_WEBPAGES = WebpageWebpages.WEBPAGE_WEBPAGES;

  /** The table <code>public.webpages</code>. */
  public static final Webpages WEBPAGES = Webpages.WEBPAGES;

  /** The table <code>public.website_webpages</code>. */
  public static final WebsiteWebpages WEBSITE_WEBPAGES = WebsiteWebpages.WEBSITE_WEBPAGES;

  /** The table <code>public.websites</code>. */
  public static final Websites WEBSITES = Websites.WEBSITES;

  /** The table <code>public.work_creators</code>. */
  public static final WorkCreators WORK_CREATORS = WorkCreators.WORK_CREATORS;

  /** The table <code>public.works</code>. */
  public static final Works WORKS = Works.WORKS;
}
