/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Articles;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ArticlesRecord extends UpdatableRecordImpl<ArticlesRecord>
    implements Record14<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        JSONB,
        Integer,
        UUID,
        JSONB,
        JSONB,
        LocalDate,
        JSONB> {

  private static final long serialVersionUID = 1247958408;

  /** Setter for <code>public.articles.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.articles.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.articles.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.articles.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.articles.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.articles.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.articles.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.articles.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.articles.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.articles.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.articles.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.articles.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.articles.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.articles.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.articles.text</code>. */
  public void setText(JSONB value) {
    set(7, value);
  }

  /** Getter for <code>public.articles.text</code>. */
  public JSONB getText() {
    return (JSONB) get(7);
  }

  /** Setter for <code>public.articles.refid</code>. */
  public void setRefid(Integer value) {
    set(8, value);
  }

  /** Getter for <code>public.articles.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(8);
  }

  /** Setter for <code>public.articles.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(9, value);
  }

  /** Getter for <code>public.articles.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(9);
  }

  /** Setter for <code>public.articles.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(10, value);
  }

  /** Getter for <code>public.articles.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(10);
  }

  /** Setter for <code>public.articles.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(11, value);
  }

  /** Getter for <code>public.articles.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(11);
  }

  /** Setter for <code>public.articles.date_published</code>. */
  public void setDatePublished(LocalDate value) {
    set(12, value);
  }

  /** Getter for <code>public.articles.date_published</code>. */
  public LocalDate getDatePublished() {
    return (LocalDate) get(12);
  }

  /** Setter for <code>public.articles.timevalue_published</code>. */
  public void setTimevaluePublished(JSONB value) {
    set(13, value);
  }

  /** Getter for <code>public.articles.timevalue_published</code>. */
  public JSONB getTimevaluePublished() {
    return (JSONB) get(13);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record14 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          JSONB,
          Integer,
          UUID,
          JSONB,
          JSONB,
          LocalDate,
          JSONB>
      fieldsRow() {
    return (Row14) super.fieldsRow();
  }

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          JSONB,
          Integer,
          UUID,
          JSONB,
          JSONB,
          LocalDate,
          JSONB>
      valuesRow() {
    return (Row14) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Articles.ARTICLES.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Articles.ARTICLES.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Articles.ARTICLES.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Articles.ARTICLES.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Articles.ARTICLES.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Articles.ARTICLES.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Articles.ARTICLES.ENTITY_TYPE;
  }

  @Override
  public Field<JSONB> field8() {
    return Articles.ARTICLES.TEXT;
  }

  @Override
  public Field<Integer> field9() {
    return Articles.ARTICLES.REFID;
  }

  @Override
  public Field<UUID> field10() {
    return Articles.ARTICLES.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field11() {
    return Articles.ARTICLES.PREVIEW_HINTS;
  }

  @Override
  public Field<JSONB> field12() {
    return Articles.ARTICLES.CUSTOM_ATTRS;
  }

  @Override
  public Field<LocalDate> field13() {
    return Articles.ARTICLES.DATE_PUBLISHED;
  }

  @Override
  public Field<JSONB> field14() {
    return Articles.ARTICLES.TIMEVALUE_PUBLISHED;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public JSONB component8() {
    return getText();
  }

  @Override
  public Integer component9() {
    return getRefid();
  }

  @Override
  public UUID component10() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component11() {
    return getPreviewHints();
  }

  @Override
  public JSONB component12() {
    return getCustomAttrs();
  }

  @Override
  public LocalDate component13() {
    return getDatePublished();
  }

  @Override
  public JSONB component14() {
    return getTimevaluePublished();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public JSONB value8() {
    return getText();
  }

  @Override
  public Integer value9() {
    return getRefid();
  }

  @Override
  public UUID value10() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value11() {
    return getPreviewHints();
  }

  @Override
  public JSONB value12() {
    return getCustomAttrs();
  }

  @Override
  public LocalDate value13() {
    return getDatePublished();
  }

  @Override
  public JSONB value14() {
    return getTimevaluePublished();
  }

  @Override
  public ArticlesRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public ArticlesRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public ArticlesRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public ArticlesRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public ArticlesRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public ArticlesRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public ArticlesRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public ArticlesRecord value8(JSONB value) {
    setText(value);
    return this;
  }

  @Override
  public ArticlesRecord value9(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public ArticlesRecord value10(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public ArticlesRecord value11(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public ArticlesRecord value12(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public ArticlesRecord value13(LocalDate value) {
    setDatePublished(value);
    return this;
  }

  @Override
  public ArticlesRecord value14(JSONB value) {
    setTimevaluePublished(value);
    return this;
  }

  @Override
  public ArticlesRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      JSONB value8,
      Integer value9,
      UUID value10,
      JSONB value11,
      JSONB value12,
      LocalDate value13,
      JSONB value14) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    value14(value14);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ArticlesRecord */
  public ArticlesRecord() {
    super(Articles.ARTICLES);
  }

  /** Create a detached, initialised ArticlesRecord */
  public ArticlesRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      JSONB text,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      JSONB customAttrs,
      LocalDate datePublished,
      JSONB timevaluePublished) {
    super(Articles.ARTICLES);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, text);
    set(8, refid);
    set(9, previewfileresource);
    set(10, previewHints);
    set(11, customAttrs);
    set(12, datePublished);
    set(13, timevaluePublished);
  }
}
