/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ArticleCreators;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ArticleCreatorsRecord extends UpdatableRecordImpl<ArticleCreatorsRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = 611643349;

  /** Setter for <code>public.article_creators.article_uuid</code>. */
  public void setArticleUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.article_creators.article_uuid</code>. */
  public UUID getArticleUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.article_creators.agent_uuid</code>. */
  public void setAgentUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.article_creators.agent_uuid</code>. */
  public UUID getAgentUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.article_creators.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.article_creators.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return ArticleCreators.ARTICLE_CREATORS.ARTICLE_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return ArticleCreators.ARTICLE_CREATORS.AGENT_UUID;
  }

  @Override
  public Field<Short> field3() {
    return ArticleCreators.ARTICLE_CREATORS.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getArticleUuid();
  }

  @Override
  public UUID component2() {
    return getAgentUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getArticleUuid();
  }

  @Override
  public UUID value2() {
    return getAgentUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public ArticleCreatorsRecord value1(UUID value) {
    setArticleUuid(value);
    return this;
  }

  @Override
  public ArticleCreatorsRecord value2(UUID value) {
    setAgentUuid(value);
    return this;
  }

  @Override
  public ArticleCreatorsRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public ArticleCreatorsRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ArticleCreatorsRecord */
  public ArticleCreatorsRecord() {
    super(ArticleCreators.ARTICLE_CREATORS);
  }

  /** Create a detached, initialised ArticleCreatorsRecord */
  public ArticleCreatorsRecord(UUID articleUuid, UUID agentUuid, Short sortindex) {
    super(ArticleCreators.ARTICLE_CREATORS);

    set(0, articleUuid);
    set(1, agentUuid);
    set(2, sortindex);
  }
}
