/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.CollectionCollections;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CollectionCollectionsRecord extends UpdatableRecordImpl<CollectionCollectionsRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = -954567355;

  /** Setter for <code>public.collection_collections.parent_collection_uuid</code>. */
  public void setParentCollectionUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.collection_collections.parent_collection_uuid</code>. */
  public UUID getParentCollectionUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.collection_collections.child_collection_uuid</code>. */
  public void setChildCollectionUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.collection_collections.child_collection_uuid</code>. */
  public UUID getChildCollectionUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.collection_collections.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.collection_collections.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return CollectionCollections.COLLECTION_COLLECTIONS.PARENT_COLLECTION_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return CollectionCollections.COLLECTION_COLLECTIONS.CHILD_COLLECTION_UUID;
  }

  @Override
  public Field<Short> field3() {
    return CollectionCollections.COLLECTION_COLLECTIONS.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getParentCollectionUuid();
  }

  @Override
  public UUID component2() {
    return getChildCollectionUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getParentCollectionUuid();
  }

  @Override
  public UUID value2() {
    return getChildCollectionUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public CollectionCollectionsRecord value1(UUID value) {
    setParentCollectionUuid(value);
    return this;
  }

  @Override
  public CollectionCollectionsRecord value2(UUID value) {
    setChildCollectionUuid(value);
    return this;
  }

  @Override
  public CollectionCollectionsRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public CollectionCollectionsRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached CollectionCollectionsRecord */
  public CollectionCollectionsRecord() {
    super(CollectionCollections.COLLECTION_COLLECTIONS);
  }

  /** Create a detached, initialised CollectionCollectionsRecord */
  public CollectionCollectionsRecord(
      UUID parentCollectionUuid, UUID childCollectionUuid, Short sortindex) {
    super(CollectionCollections.COLLECTION_COLLECTIONS);

    set(0, parentCollectionUuid);
    set(1, childCollectionUuid);
    set(2, sortindex);
  }
}
