/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Corporatebodies;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class CorporatebodiesRecord extends UpdatableRecordImpl<CorporatebodiesRecord>
    implements Record14<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        Integer,
        JSONB,
        String,
        Integer,
        UUID,
        JSONB,
        JSONB> {

  private static final long serialVersionUID = 549945102;

  /** Setter for <code>public.corporatebodies.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.corporatebodies.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.corporatebodies.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.corporatebodies.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.corporatebodies.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.corporatebodies.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.corporatebodies.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.corporatebodies.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.corporatebodies.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.corporatebodies.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.corporatebodies.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.corporatebodies.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.corporatebodies.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.corporatebodies.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.corporatebodies.id</code>. */
  public void setId(Integer value) {
    set(7, value);
  }

  /** Getter for <code>public.corporatebodies.id</code>. */
  public Integer getId() {
    return (Integer) get(7);
  }

  /** Setter for <code>public.corporatebodies.text</code>. */
  public void setText(JSONB value) {
    set(8, value);
  }

  /** Getter for <code>public.corporatebodies.text</code>. */
  public JSONB getText() {
    return (JSONB) get(8);
  }

  /** Setter for <code>public.corporatebodies.homepage_url</code>. */
  public void setHomepageUrl(String value) {
    set(9, value);
  }

  /** Getter for <code>public.corporatebodies.homepage_url</code>. */
  public String getHomepageUrl() {
    return (String) get(9);
  }

  /** Setter for <code>public.corporatebodies.refid</code>. */
  public void setRefid(Integer value) {
    set(10, value);
  }

  /** Getter for <code>public.corporatebodies.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(10);
  }

  /** Setter for <code>public.corporatebodies.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(11, value);
  }

  /** Getter for <code>public.corporatebodies.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(11);
  }

  /** Setter for <code>public.corporatebodies.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(12, value);
  }

  /** Getter for <code>public.corporatebodies.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(12);
  }

  /** Setter for <code>public.corporatebodies.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(13, value);
  }

  /** Getter for <code>public.corporatebodies.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(13);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<Integer> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record14 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          JSONB,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row14) super.fieldsRow();
  }

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          JSONB,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      valuesRow() {
    return (Row14) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Corporatebodies.CORPORATEBODIES.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Corporatebodies.CORPORATEBODIES.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Corporatebodies.CORPORATEBODIES.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Corporatebodies.CORPORATEBODIES.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Corporatebodies.CORPORATEBODIES.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Corporatebodies.CORPORATEBODIES.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Corporatebodies.CORPORATEBODIES.ENTITY_TYPE;
  }

  @Override
  public Field<Integer> field8() {
    return Corporatebodies.CORPORATEBODIES.ID;
  }

  @Override
  public Field<JSONB> field9() {
    return Corporatebodies.CORPORATEBODIES.TEXT;
  }

  @Override
  public Field<String> field10() {
    return Corporatebodies.CORPORATEBODIES.HOMEPAGE_URL;
  }

  @Override
  public Field<Integer> field11() {
    return Corporatebodies.CORPORATEBODIES.REFID;
  }

  @Override
  public Field<UUID> field12() {
    return Corporatebodies.CORPORATEBODIES.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field13() {
    return Corporatebodies.CORPORATEBODIES.PREVIEW_HINTS;
  }

  @Override
  public Field<JSONB> field14() {
    return Corporatebodies.CORPORATEBODIES.CUSTOM_ATTRS;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public Integer component8() {
    return getId();
  }

  @Override
  public JSONB component9() {
    return getText();
  }

  @Override
  public String component10() {
    return getHomepageUrl();
  }

  @Override
  public Integer component11() {
    return getRefid();
  }

  @Override
  public UUID component12() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component13() {
    return getPreviewHints();
  }

  @Override
  public JSONB component14() {
    return getCustomAttrs();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public Integer value8() {
    return getId();
  }

  @Override
  public JSONB value9() {
    return getText();
  }

  @Override
  public String value10() {
    return getHomepageUrl();
  }

  @Override
  public Integer value11() {
    return getRefid();
  }

  @Override
  public UUID value12() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value13() {
    return getPreviewHints();
  }

  @Override
  public JSONB value14() {
    return getCustomAttrs();
  }

  @Override
  public CorporatebodiesRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value8(Integer value) {
    setId(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value9(JSONB value) {
    setText(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value10(String value) {
    setHomepageUrl(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value11(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value12(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value13(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord value14(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public CorporatebodiesRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      Integer value8,
      JSONB value9,
      String value10,
      Integer value11,
      UUID value12,
      JSONB value13,
      JSONB value14) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    value14(value14);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached CorporatebodiesRecord */
  public CorporatebodiesRecord() {
    super(Corporatebodies.CORPORATEBODIES);
  }

  /** Create a detached, initialised CorporatebodiesRecord */
  public CorporatebodiesRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      Integer id,
      JSONB text,
      String homepageUrl,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      JSONB customAttrs) {
    super(Corporatebodies.CORPORATEBODIES);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, id);
    set(8, text);
    set(9, homepageUrl);
    set(10, refid);
    set(11, previewfileresource);
    set(12, previewHints);
    set(13, customAttrs);
  }
}
