/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.DigitalobjectFileresources;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DigitalobjectFileresourcesRecord
    extends UpdatableRecordImpl<DigitalobjectFileresourcesRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = 2103529216;

  /** Setter for <code>public.digitalobject_fileresources.digitalobject_uuid</code>. */
  public void setDigitalobjectUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.digitalobject_fileresources.digitalobject_uuid</code>. */
  public UUID getDigitalobjectUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.digitalobject_fileresources.fileresource_uuid</code>. */
  public void setFileresourceUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.digitalobject_fileresources.fileresource_uuid</code>. */
  public UUID getFileresourceUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.digitalobject_fileresources.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.digitalobject_fileresources.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.DIGITALOBJECT_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.FILERESOURCE_UUID;
  }

  @Override
  public Field<Short> field3() {
    return DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getDigitalobjectUuid();
  }

  @Override
  public UUID component2() {
    return getFileresourceUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getDigitalobjectUuid();
  }

  @Override
  public UUID value2() {
    return getFileresourceUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public DigitalobjectFileresourcesRecord value1(UUID value) {
    setDigitalobjectUuid(value);
    return this;
  }

  @Override
  public DigitalobjectFileresourcesRecord value2(UUID value) {
    setFileresourceUuid(value);
    return this;
  }

  @Override
  public DigitalobjectFileresourcesRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public DigitalobjectFileresourcesRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached DigitalobjectFileresourcesRecord */
  public DigitalobjectFileresourcesRecord() {
    super(DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES);
  }

  /** Create a detached, initialised DigitalobjectFileresourcesRecord */
  public DigitalobjectFileresourcesRecord(
      UUID digitalobjectUuid, UUID fileresourceUuid, Short sortindex) {
    super(DigitalobjectFileresources.DIGITALOBJECT_FILERESOURCES);

    set(0, digitalobjectUuid);
    set(1, fileresourceUuid);
    set(2, sortindex);
  }
}
