/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Entities;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record11;
import org.jooq.Row11;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class EntitiesRecord extends TableRecordImpl<EntitiesRecord>
    implements Record11<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        Integer,
        UUID,
        JSONB,
        JSONB> {

  private static final long serialVersionUID = 1830606333;

  /** Setter for <code>public.entities.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.entities.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.entities.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.entities.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.entities.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.entities.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.entities.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.entities.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.entities.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.entities.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.entities.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.entities.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.entities.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.entities.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.entities.refid</code>. */
  public void setRefid(Integer value) {
    set(7, value);
  }

  /** Getter for <code>public.entities.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(7);
  }

  /** Setter for <code>public.entities.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(8, value);
  }

  /** Getter for <code>public.entities.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(8);
  }

  /** Setter for <code>public.entities.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(9, value);
  }

  /** Getter for <code>public.entities.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(9);
  }

  /** Setter for <code>public.entities.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(10, value);
  }

  /** Getter for <code>public.entities.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(10);
  }

  // -------------------------------------------------------------------------
  // Record11 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row11<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row11) super.fieldsRow();
  }

  @Override
  public Row11<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      valuesRow() {
    return (Row11) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Entities.ENTITIES.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Entities.ENTITIES.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Entities.ENTITIES.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Entities.ENTITIES.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Entities.ENTITIES.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Entities.ENTITIES.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Entities.ENTITIES.ENTITY_TYPE;
  }

  @Override
  public Field<Integer> field8() {
    return Entities.ENTITIES.REFID;
  }

  @Override
  public Field<UUID> field9() {
    return Entities.ENTITIES.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field10() {
    return Entities.ENTITIES.PREVIEW_HINTS;
  }

  @Override
  public Field<JSONB> field11() {
    return Entities.ENTITIES.CUSTOM_ATTRS;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public Integer component8() {
    return getRefid();
  }

  @Override
  public UUID component9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component10() {
    return getPreviewHints();
  }

  @Override
  public JSONB component11() {
    return getCustomAttrs();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public Integer value8() {
    return getRefid();
  }

  @Override
  public UUID value9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value10() {
    return getPreviewHints();
  }

  @Override
  public JSONB value11() {
    return getCustomAttrs();
  }

  @Override
  public EntitiesRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public EntitiesRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public EntitiesRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public EntitiesRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public EntitiesRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public EntitiesRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public EntitiesRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public EntitiesRecord value8(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public EntitiesRecord value9(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public EntitiesRecord value10(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public EntitiesRecord value11(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public EntitiesRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      Integer value8,
      UUID value9,
      JSONB value10,
      JSONB value11) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached EntitiesRecord */
  public EntitiesRecord() {
    super(Entities.ENTITIES);
  }

  /** Create a detached, initialised EntitiesRecord */
  public EntitiesRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      JSONB customAttrs) {
    super(Entities.ENTITIES);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, refid);
    set(8, previewfileresource);
    set(9, previewHints);
    set(10, customAttrs);
  }
}
