/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Fileresources;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FileresourcesRecord extends UpdatableRecordImpl<FileresourcesRecord>
    implements Record13<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        String,
        Long,
        String,
        UUID,
        JSONB,
        String> {

  private static final long serialVersionUID = -158233274;

  /** Setter for <code>public.fileresources.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.fileresources.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.fileresources.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.fileresources.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.fileresources.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.fileresources.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.fileresources.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.fileresources.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.fileresources.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.fileresources.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.fileresources.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.fileresources.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.fileresources.filename</code>. */
  public void setFilename(String value) {
    set(6, value);
  }

  /** Getter for <code>public.fileresources.filename</code>. */
  public String getFilename() {
    return (String) get(6);
  }

  /** Setter for <code>public.fileresources.mimetype</code>. */
  public void setMimetype(String value) {
    set(7, value);
  }

  /** Getter for <code>public.fileresources.mimetype</code>. */
  public String getMimetype() {
    return (String) get(7);
  }

  /** Setter for <code>public.fileresources.size_in_bytes</code>. */
  public void setSizeInBytes(Long value) {
    set(8, value);
  }

  /** Getter for <code>public.fileresources.size_in_bytes</code>. */
  public Long getSizeInBytes() {
    return (Long) get(8);
  }

  /** Setter for <code>public.fileresources.uri</code>. */
  public void setUri(String value) {
    set(9, value);
  }

  /** Getter for <code>public.fileresources.uri</code>. */
  public String getUri() {
    return (String) get(9);
  }

  /** Setter for <code>public.fileresources.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(10, value);
  }

  /** Getter for <code>public.fileresources.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(10);
  }

  /** Setter for <code>public.fileresources.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(11, value);
  }

  /** Getter for <code>public.fileresources.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(11);
  }

  /** Setter for <code>public.fileresources.http_base_url</code>. */
  public void setHttpBaseUrl(String value) {
    set(12, value);
  }

  /** Getter for <code>public.fileresources.http_base_url</code>. */
  public String getHttpBaseUrl() {
    return (String) get(12);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record13 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          Long,
          String,
          UUID,
          JSONB,
          String>
      fieldsRow() {
    return (Row13) super.fieldsRow();
  }

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          Long,
          String,
          UUID,
          JSONB,
          String>
      valuesRow() {
    return (Row13) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Fileresources.FILERESOURCES.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Fileresources.FILERESOURCES.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Fileresources.FILERESOURCES.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Fileresources.FILERESOURCES.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Fileresources.FILERESOURCES.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Fileresources.FILERESOURCES.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Fileresources.FILERESOURCES.FILENAME;
  }

  @Override
  public Field<String> field8() {
    return Fileresources.FILERESOURCES.MIMETYPE;
  }

  @Override
  public Field<Long> field9() {
    return Fileresources.FILERESOURCES.SIZE_IN_BYTES;
  }

  @Override
  public Field<String> field10() {
    return Fileresources.FILERESOURCES.URI;
  }

  @Override
  public Field<UUID> field11() {
    return Fileresources.FILERESOURCES.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field12() {
    return Fileresources.FILERESOURCES.PREVIEW_HINTS;
  }

  @Override
  public Field<String> field13() {
    return Fileresources.FILERESOURCES.HTTP_BASE_URL;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getFilename();
  }

  @Override
  public String component8() {
    return getMimetype();
  }

  @Override
  public Long component9() {
    return getSizeInBytes();
  }

  @Override
  public String component10() {
    return getUri();
  }

  @Override
  public UUID component11() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component12() {
    return getPreviewHints();
  }

  @Override
  public String component13() {
    return getHttpBaseUrl();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getFilename();
  }

  @Override
  public String value8() {
    return getMimetype();
  }

  @Override
  public Long value9() {
    return getSizeInBytes();
  }

  @Override
  public String value10() {
    return getUri();
  }

  @Override
  public UUID value11() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value12() {
    return getPreviewHints();
  }

  @Override
  public String value13() {
    return getHttpBaseUrl();
  }

  @Override
  public FileresourcesRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public FileresourcesRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public FileresourcesRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public FileresourcesRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public FileresourcesRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public FileresourcesRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public FileresourcesRecord value7(String value) {
    setFilename(value);
    return this;
  }

  @Override
  public FileresourcesRecord value8(String value) {
    setMimetype(value);
    return this;
  }

  @Override
  public FileresourcesRecord value9(Long value) {
    setSizeInBytes(value);
    return this;
  }

  @Override
  public FileresourcesRecord value10(String value) {
    setUri(value);
    return this;
  }

  @Override
  public FileresourcesRecord value11(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public FileresourcesRecord value12(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public FileresourcesRecord value13(String value) {
    setHttpBaseUrl(value);
    return this;
  }

  @Override
  public FileresourcesRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      String value8,
      Long value9,
      String value10,
      UUID value11,
      JSONB value12,
      String value13) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached FileresourcesRecord */
  public FileresourcesRecord() {
    super(Fileresources.FILERESOURCES);
  }

  /** Create a detached, initialised FileresourcesRecord */
  public FileresourcesRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String filename,
      String mimetype,
      Long sizeInBytes,
      String uri,
      UUID previewfileresource,
      JSONB previewHints,
      String httpBaseUrl) {
    super(Fileresources.FILERESOURCES);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, filename);
    set(7, mimetype);
    set(8, sizeInBytes);
    set(9, uri);
    set(10, previewfileresource);
    set(11, previewHints);
    set(12, httpBaseUrl);
  }
}
