/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Humansettlements;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record14;
import org.jooq.Row14;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HumansettlementsRecord extends TableRecordImpl<HumansettlementsRecord>
    implements Record14<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        Integer,
        UUID,
        JSONB,
        JSONB,
        String,
        JSONB,
        String> {

  private static final long serialVersionUID = -1121003806;

  /** Setter for <code>public.humansettlements.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.humansettlements.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.humansettlements.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.humansettlements.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.humansettlements.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.humansettlements.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.humansettlements.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.humansettlements.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.humansettlements.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.humansettlements.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.humansettlements.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.humansettlements.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.humansettlements.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.humansettlements.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.humansettlements.refid</code>. */
  public void setRefid(Integer value) {
    set(7, value);
  }

  /** Getter for <code>public.humansettlements.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(7);
  }

  /** Setter for <code>public.humansettlements.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(8, value);
  }

  /** Getter for <code>public.humansettlements.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(8);
  }

  /** Setter for <code>public.humansettlements.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(9, value);
  }

  /** Getter for <code>public.humansettlements.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(9);
  }

  /** Setter for <code>public.humansettlements.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(10, value);
  }

  /** Getter for <code>public.humansettlements.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(10);
  }

  /** Setter for <code>public.humansettlements.geolocation_type</code>. */
  public void setGeolocationType(String value) {
    set(11, value);
  }

  /** Getter for <code>public.humansettlements.geolocation_type</code>. */
  public String getGeolocationType() {
    return (String) get(11);
  }

  /** Setter for <code>public.humansettlements.coordinate_location</code>. */
  public void setCoordinateLocation(JSONB value) {
    set(12, value);
  }

  /** Getter for <code>public.humansettlements.coordinate_location</code>. */
  public JSONB getCoordinateLocation() {
    return (JSONB) get(12);
  }

  /** Setter for <code>public.humansettlements.settlement_type</code>. */
  public void setSettlementType(String value) {
    set(13, value);
  }

  /** Getter for <code>public.humansettlements.settlement_type</code>. */
  public String getSettlementType() {
    return (String) get(13);
  }

  // -------------------------------------------------------------------------
  // Record14 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB,
          String,
          JSONB,
          String>
      fieldsRow() {
    return (Row14) super.fieldsRow();
  }

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB,
          String,
          JSONB,
          String>
      valuesRow() {
    return (Row14) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Humansettlements.HUMANSETTLEMENTS.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Humansettlements.HUMANSETTLEMENTS.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Humansettlements.HUMANSETTLEMENTS.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Humansettlements.HUMANSETTLEMENTS.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Humansettlements.HUMANSETTLEMENTS.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Humansettlements.HUMANSETTLEMENTS.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Humansettlements.HUMANSETTLEMENTS.ENTITY_TYPE;
  }

  @Override
  public Field<Integer> field8() {
    return Humansettlements.HUMANSETTLEMENTS.REFID;
  }

  @Override
  public Field<UUID> field9() {
    return Humansettlements.HUMANSETTLEMENTS.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field10() {
    return Humansettlements.HUMANSETTLEMENTS.PREVIEW_HINTS;
  }

  @Override
  public Field<JSONB> field11() {
    return Humansettlements.HUMANSETTLEMENTS.CUSTOM_ATTRS;
  }

  @Override
  public Field<String> field12() {
    return Humansettlements.HUMANSETTLEMENTS.GEOLOCATION_TYPE;
  }

  @Override
  public Field<JSONB> field13() {
    return Humansettlements.HUMANSETTLEMENTS.COORDINATE_LOCATION;
  }

  @Override
  public Field<String> field14() {
    return Humansettlements.HUMANSETTLEMENTS.SETTLEMENT_TYPE;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public Integer component8() {
    return getRefid();
  }

  @Override
  public UUID component9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component10() {
    return getPreviewHints();
  }

  @Override
  public JSONB component11() {
    return getCustomAttrs();
  }

  @Override
  public String component12() {
    return getGeolocationType();
  }

  @Override
  public JSONB component13() {
    return getCoordinateLocation();
  }

  @Override
  public String component14() {
    return getSettlementType();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public Integer value8() {
    return getRefid();
  }

  @Override
  public UUID value9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value10() {
    return getPreviewHints();
  }

  @Override
  public JSONB value11() {
    return getCustomAttrs();
  }

  @Override
  public String value12() {
    return getGeolocationType();
  }

  @Override
  public JSONB value13() {
    return getCoordinateLocation();
  }

  @Override
  public String value14() {
    return getSettlementType();
  }

  @Override
  public HumansettlementsRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value8(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value9(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value10(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value11(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value12(String value) {
    setGeolocationType(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value13(JSONB value) {
    setCoordinateLocation(value);
    return this;
  }

  @Override
  public HumansettlementsRecord value14(String value) {
    setSettlementType(value);
    return this;
  }

  @Override
  public HumansettlementsRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      Integer value8,
      UUID value9,
      JSONB value10,
      JSONB value11,
      String value12,
      JSONB value13,
      String value14) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    value14(value14);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached HumansettlementsRecord */
  public HumansettlementsRecord() {
    super(Humansettlements.HUMANSETTLEMENTS);
  }

  /** Create a detached, initialised HumansettlementsRecord */
  public HumansettlementsRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      JSONB customAttrs,
      String geolocationType,
      JSONB coordinateLocation,
      String settlementType) {
    super(Humansettlements.HUMANSETTLEMENTS);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, refid);
    set(8, previewfileresource);
    set(9, previewHints);
    set(10, customAttrs);
    set(11, geolocationType);
    set(12, coordinateLocation);
    set(13, settlementType);
  }
}
