/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ItemWorks;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ItemWorksRecord extends UpdatableRecordImpl<ItemWorksRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = -1090250191;

  /** Setter for <code>public.item_works.item_uuid</code>. */
  public void setItemUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.item_works.item_uuid</code>. */
  public UUID getItemUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.item_works.work_uuid</code>. */
  public void setWorkUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.item_works.work_uuid</code>. */
  public UUID getWorkUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.item_works.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.item_works.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return ItemWorks.ITEM_WORKS.ITEM_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return ItemWorks.ITEM_WORKS.WORK_UUID;
  }

  @Override
  public Field<Short> field3() {
    return ItemWorks.ITEM_WORKS.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getItemUuid();
  }

  @Override
  public UUID component2() {
    return getWorkUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getItemUuid();
  }

  @Override
  public UUID value2() {
    return getWorkUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public ItemWorksRecord value1(UUID value) {
    setItemUuid(value);
    return this;
  }

  @Override
  public ItemWorksRecord value2(UUID value) {
    setWorkUuid(value);
    return this;
  }

  @Override
  public ItemWorksRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public ItemWorksRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ItemWorksRecord */
  public ItemWorksRecord() {
    super(ItemWorks.ITEM_WORKS);
  }

  /** Create a detached, initialised ItemWorksRecord */
  public ItemWorksRecord(UUID itemUuid, UUID workUuid, Short sortindex) {
    super(ItemWorks.ITEM_WORKS);

    set(0, itemUuid);
    set(1, workUuid);
    set(2, sortindex);
  }
}
