/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Items;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ItemsRecord extends TableRecordImpl<ItemsRecord>
    implements Record16<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        Integer,
        UUID,
        JSONB,
        String,
        String,
        String,
        String,
        String,
        JSONB> {

  private static final long serialVersionUID = 68124597;

  /** Setter for <code>public.items.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.items.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.items.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.items.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.items.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.items.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.items.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.items.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.items.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.items.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.items.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.items.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.items.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.items.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.items.refid</code>. */
  public void setRefid(Integer value) {
    set(7, value);
  }

  /** Getter for <code>public.items.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(7);
  }

  /** Setter for <code>public.items.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(8, value);
  }

  /** Getter for <code>public.items.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(8);
  }

  /** Setter for <code>public.items.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(9, value);
  }

  /** Getter for <code>public.items.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(9);
  }

  /** Setter for <code>public.items.language</code>. */
  public void setLanguage(String value) {
    set(10, value);
  }

  /** Getter for <code>public.items.language</code>. */
  public String getLanguage() {
    return (String) get(10);
  }

  /** Setter for <code>public.items.publication_date</code>. */
  public void setPublicationDate(String value) {
    set(11, value);
  }

  /** Getter for <code>public.items.publication_date</code>. */
  public String getPublicationDate() {
    return (String) get(11);
  }

  /** Setter for <code>public.items.publication_place</code>. */
  public void setPublicationPlace(String value) {
    set(12, value);
  }

  /** Getter for <code>public.items.publication_place</code>. */
  public String getPublicationPlace() {
    return (String) get(12);
  }

  /** Setter for <code>public.items.publisher</code>. */
  public void setPublisher(String value) {
    set(13, value);
  }

  /** Getter for <code>public.items.publisher</code>. */
  public String getPublisher() {
    return (String) get(13);
  }

  /** Setter for <code>public.items.version</code>. */
  public void setVersion(String value) {
    set(14, value);
  }

  /** Getter for <code>public.items.version</code>. */
  public String getVersion() {
    return (String) get(14);
  }

  /** Setter for <code>public.items.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(15, value);
  }

  /** Getter for <code>public.items.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(15);
  }

  // -------------------------------------------------------------------------
  // Record16 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row16<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          String,
          String,
          String,
          String,
          String,
          JSONB>
      fieldsRow() {
    return (Row16) super.fieldsRow();
  }

  @Override
  public Row16<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          String,
          String,
          String,
          String,
          String,
          JSONB>
      valuesRow() {
    return (Row16) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Items.ITEMS.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Items.ITEMS.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Items.ITEMS.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Items.ITEMS.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Items.ITEMS.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Items.ITEMS.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Items.ITEMS.ENTITY_TYPE;
  }

  @Override
  public Field<Integer> field8() {
    return Items.ITEMS.REFID;
  }

  @Override
  public Field<UUID> field9() {
    return Items.ITEMS.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field10() {
    return Items.ITEMS.PREVIEW_HINTS;
  }

  @Override
  public Field<String> field11() {
    return Items.ITEMS.LANGUAGE;
  }

  @Override
  public Field<String> field12() {
    return Items.ITEMS.PUBLICATION_DATE;
  }

  @Override
  public Field<String> field13() {
    return Items.ITEMS.PUBLICATION_PLACE;
  }

  @Override
  public Field<String> field14() {
    return Items.ITEMS.PUBLISHER;
  }

  @Override
  public Field<String> field15() {
    return Items.ITEMS.VERSION;
  }

  @Override
  public Field<JSONB> field16() {
    return Items.ITEMS.CUSTOM_ATTRS;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public Integer component8() {
    return getRefid();
  }

  @Override
  public UUID component9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component10() {
    return getPreviewHints();
  }

  @Override
  public String component11() {
    return getLanguage();
  }

  @Override
  public String component12() {
    return getPublicationDate();
  }

  @Override
  public String component13() {
    return getPublicationPlace();
  }

  @Override
  public String component14() {
    return getPublisher();
  }

  @Override
  public String component15() {
    return getVersion();
  }

  @Override
  public JSONB component16() {
    return getCustomAttrs();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public Integer value8() {
    return getRefid();
  }

  @Override
  public UUID value9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value10() {
    return getPreviewHints();
  }

  @Override
  public String value11() {
    return getLanguage();
  }

  @Override
  public String value12() {
    return getPublicationDate();
  }

  @Override
  public String value13() {
    return getPublicationPlace();
  }

  @Override
  public String value14() {
    return getPublisher();
  }

  @Override
  public String value15() {
    return getVersion();
  }

  @Override
  public JSONB value16() {
    return getCustomAttrs();
  }

  @Override
  public ItemsRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public ItemsRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public ItemsRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public ItemsRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public ItemsRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public ItemsRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public ItemsRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public ItemsRecord value8(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public ItemsRecord value9(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public ItemsRecord value10(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public ItemsRecord value11(String value) {
    setLanguage(value);
    return this;
  }

  @Override
  public ItemsRecord value12(String value) {
    setPublicationDate(value);
    return this;
  }

  @Override
  public ItemsRecord value13(String value) {
    setPublicationPlace(value);
    return this;
  }

  @Override
  public ItemsRecord value14(String value) {
    setPublisher(value);
    return this;
  }

  @Override
  public ItemsRecord value15(String value) {
    setVersion(value);
    return this;
  }

  @Override
  public ItemsRecord value16(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public ItemsRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      Integer value8,
      UUID value9,
      JSONB value10,
      String value11,
      String value12,
      String value13,
      String value14,
      String value15,
      JSONB value16) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    value14(value14);
    value15(value15);
    value16(value16);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ItemsRecord */
  public ItemsRecord() {
    super(Items.ITEMS);
  }

  /** Create a detached, initialised ItemsRecord */
  public ItemsRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      String language,
      String publicationDate,
      String publicationPlace,
      String publisher,
      String version,
      JSONB customAttrs) {
    super(Items.ITEMS);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, refid);
    set(8, previewfileresource);
    set(9, previewHints);
    set(10, language);
    set(11, publicationDate);
    set(12, publicationPlace);
    set(13, publisher);
    set(14, version);
    set(15, customAttrs);
  }
}
