/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.ItemDigitalobjects;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ItemDigitalobjectsRecord extends UpdatableRecordImpl<ItemDigitalobjectsRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = -1847485959;

  /** Setter for <code>public.item_digitalobjects.item_uuid</code>. */
  public void setItemUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.item_digitalobjects.item_uuid</code>. */
  public UUID getItemUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.item_digitalobjects.digitalobject_uuid</code>. */
  public void setDigitalobjectUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.item_digitalobjects.digitalobject_uuid</code>. */
  public UUID getDigitalobjectUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.item_digitalobjects.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.item_digitalobjects.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return ItemDigitalobjects.ITEM_DIGITALOBJECTS.ITEM_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return ItemDigitalobjects.ITEM_DIGITALOBJECTS.DIGITALOBJECT_UUID;
  }

  @Override
  public Field<Short> field3() {
    return ItemDigitalobjects.ITEM_DIGITALOBJECTS.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getItemUuid();
  }

  @Override
  public UUID component2() {
    return getDigitalobjectUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getItemUuid();
  }

  @Override
  public UUID value2() {
    return getDigitalobjectUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public ItemDigitalobjectsRecord value1(UUID value) {
    setItemUuid(value);
    return this;
  }

  @Override
  public ItemDigitalobjectsRecord value2(UUID value) {
    setDigitalobjectUuid(value);
    return this;
  }

  @Override
  public ItemDigitalobjectsRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public ItemDigitalobjectsRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached ItemDigitalobjectsRecord */
  public ItemDigitalobjectsRecord() {
    super(ItemDigitalobjects.ITEM_DIGITALOBJECTS);
  }

  /** Create a detached, initialised ItemDigitalobjectsRecord */
  public ItemDigitalobjectsRecord(UUID itemUuid, UUID digitalobjectUuid, Short sortindex) {
    super(ItemDigitalobjects.ITEM_DIGITALOBJECTS);

    set(0, itemUuid);
    set(1, digitalobjectUuid);
    set(2, sortindex);
  }
}
