/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Persons;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record18;
import org.jooq.Row18;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class PersonsRecord extends TableRecordImpl<PersonsRecord>
    implements Record18<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        Integer,
        UUID,
        JSONB,
        LocalDate,
        JSONB,
        LocalDate,
        JSONB,
        String,
        JSONB,
        UUID,
        UUID> {

  private static final long serialVersionUID = 662480975;

  /** Setter for <code>public.persons.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.persons.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.persons.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.persons.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.persons.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.persons.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.persons.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.persons.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.persons.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.persons.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.persons.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.persons.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.persons.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.persons.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.persons.refid</code>. */
  public void setRefid(Integer value) {
    set(7, value);
  }

  /** Getter for <code>public.persons.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(7);
  }

  /** Setter for <code>public.persons.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(8, value);
  }

  /** Getter for <code>public.persons.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(8);
  }

  /** Setter for <code>public.persons.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(9, value);
  }

  /** Getter for <code>public.persons.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(9);
  }

  /** Setter for <code>public.persons.dateofbirth</code>. */
  public void setDateofbirth(LocalDate value) {
    set(10, value);
  }

  /** Getter for <code>public.persons.dateofbirth</code>. */
  public LocalDate getDateofbirth() {
    return (LocalDate) get(10);
  }

  /** Setter for <code>public.persons.timevalueofbirth</code>. */
  public void setTimevalueofbirth(JSONB value) {
    set(11, value);
  }

  /** Getter for <code>public.persons.timevalueofbirth</code>. */
  public JSONB getTimevalueofbirth() {
    return (JSONB) get(11);
  }

  /** Setter for <code>public.persons.dateofdeath</code>. */
  public void setDateofdeath(LocalDate value) {
    set(12, value);
  }

  /** Getter for <code>public.persons.dateofdeath</code>. */
  public LocalDate getDateofdeath() {
    return (LocalDate) get(12);
  }

  /** Setter for <code>public.persons.timevalueofdeath</code>. */
  public void setTimevalueofdeath(JSONB value) {
    set(13, value);
  }

  /** Getter for <code>public.persons.timevalueofdeath</code>. */
  public JSONB getTimevalueofdeath() {
    return (JSONB) get(13);
  }

  /** Setter for <code>public.persons.gender</code>. */
  public void setGender(String value) {
    set(14, value);
  }

  /** Getter for <code>public.persons.gender</code>. */
  public String getGender() {
    return (String) get(14);
  }

  /** Setter for <code>public.persons.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(15, value);
  }

  /** Getter for <code>public.persons.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(15);
  }

  /** Setter for <code>public.persons.locationofbirth</code>. */
  public void setLocationofbirth(UUID value) {
    set(16, value);
  }

  /** Getter for <code>public.persons.locationofbirth</code>. */
  public UUID getLocationofbirth() {
    return (UUID) get(16);
  }

  /** Setter for <code>public.persons.locationofdeath</code>. */
  public void setLocationofdeath(UUID value) {
    set(17, value);
  }

  /** Getter for <code>public.persons.locationofdeath</code>. */
  public UUID getLocationofdeath() {
    return (UUID) get(17);
  }

  // -------------------------------------------------------------------------
  // Record18 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row18<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          LocalDate,
          JSONB,
          LocalDate,
          JSONB,
          String,
          JSONB,
          UUID,
          UUID>
      fieldsRow() {
    return (Row18) super.fieldsRow();
  }

  @Override
  public Row18<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          LocalDate,
          JSONB,
          LocalDate,
          JSONB,
          String,
          JSONB,
          UUID,
          UUID>
      valuesRow() {
    return (Row18) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Persons.PERSONS.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Persons.PERSONS.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Persons.PERSONS.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Persons.PERSONS.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Persons.PERSONS.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Persons.PERSONS.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Persons.PERSONS.ENTITY_TYPE;
  }

  @Override
  public Field<Integer> field8() {
    return Persons.PERSONS.REFID;
  }

  @Override
  public Field<UUID> field9() {
    return Persons.PERSONS.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field10() {
    return Persons.PERSONS.PREVIEW_HINTS;
  }

  @Override
  public Field<LocalDate> field11() {
    return Persons.PERSONS.DATEOFBIRTH;
  }

  @Override
  public Field<JSONB> field12() {
    return Persons.PERSONS.TIMEVALUEOFBIRTH;
  }

  @Override
  public Field<LocalDate> field13() {
    return Persons.PERSONS.DATEOFDEATH;
  }

  @Override
  public Field<JSONB> field14() {
    return Persons.PERSONS.TIMEVALUEOFDEATH;
  }

  @Override
  public Field<String> field15() {
    return Persons.PERSONS.GENDER;
  }

  @Override
  public Field<JSONB> field16() {
    return Persons.PERSONS.CUSTOM_ATTRS;
  }

  @Override
  public Field<UUID> field17() {
    return Persons.PERSONS.LOCATIONOFBIRTH;
  }

  @Override
  public Field<UUID> field18() {
    return Persons.PERSONS.LOCATIONOFDEATH;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public Integer component8() {
    return getRefid();
  }

  @Override
  public UUID component9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component10() {
    return getPreviewHints();
  }

  @Override
  public LocalDate component11() {
    return getDateofbirth();
  }

  @Override
  public JSONB component12() {
    return getTimevalueofbirth();
  }

  @Override
  public LocalDate component13() {
    return getDateofdeath();
  }

  @Override
  public JSONB component14() {
    return getTimevalueofdeath();
  }

  @Override
  public String component15() {
    return getGender();
  }

  @Override
  public JSONB component16() {
    return getCustomAttrs();
  }

  @Override
  public UUID component17() {
    return getLocationofbirth();
  }

  @Override
  public UUID component18() {
    return getLocationofdeath();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public Integer value8() {
    return getRefid();
  }

  @Override
  public UUID value9() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value10() {
    return getPreviewHints();
  }

  @Override
  public LocalDate value11() {
    return getDateofbirth();
  }

  @Override
  public JSONB value12() {
    return getTimevalueofbirth();
  }

  @Override
  public LocalDate value13() {
    return getDateofdeath();
  }

  @Override
  public JSONB value14() {
    return getTimevalueofdeath();
  }

  @Override
  public String value15() {
    return getGender();
  }

  @Override
  public JSONB value16() {
    return getCustomAttrs();
  }

  @Override
  public UUID value17() {
    return getLocationofbirth();
  }

  @Override
  public UUID value18() {
    return getLocationofdeath();
  }

  @Override
  public PersonsRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public PersonsRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public PersonsRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public PersonsRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public PersonsRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public PersonsRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public PersonsRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public PersonsRecord value8(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public PersonsRecord value9(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public PersonsRecord value10(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public PersonsRecord value11(LocalDate value) {
    setDateofbirth(value);
    return this;
  }

  @Override
  public PersonsRecord value12(JSONB value) {
    setTimevalueofbirth(value);
    return this;
  }

  @Override
  public PersonsRecord value13(LocalDate value) {
    setDateofdeath(value);
    return this;
  }

  @Override
  public PersonsRecord value14(JSONB value) {
    setTimevalueofdeath(value);
    return this;
  }

  @Override
  public PersonsRecord value15(String value) {
    setGender(value);
    return this;
  }

  @Override
  public PersonsRecord value16(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public PersonsRecord value17(UUID value) {
    setLocationofbirth(value);
    return this;
  }

  @Override
  public PersonsRecord value18(UUID value) {
    setLocationofdeath(value);
    return this;
  }

  @Override
  public PersonsRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      Integer value8,
      UUID value9,
      JSONB value10,
      LocalDate value11,
      JSONB value12,
      LocalDate value13,
      JSONB value14,
      String value15,
      JSONB value16,
      UUID value17,
      UUID value18) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    value14(value14);
    value15(value15);
    value16(value16);
    value17(value17);
    value18(value18);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached PersonsRecord */
  public PersonsRecord() {
    super(Persons.PERSONS);
  }

  /** Create a detached, initialised PersonsRecord */
  public PersonsRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      LocalDate dateofbirth,
      JSONB timevalueofbirth,
      LocalDate dateofdeath,
      JSONB timevalueofdeath,
      String gender,
      JSONB customAttrs,
      UUID locationofbirth,
      UUID locationofdeath) {
    super(Persons.PERSONS);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, refid);
    set(8, previewfileresource);
    set(9, previewHints);
    set(10, dateofbirth);
    set(11, timevalueofbirth);
    set(12, dateofdeath);
    set(13, timevalueofdeath);
    set(14, gender);
    set(15, customAttrs);
    set(16, locationofbirth);
    set(17, locationofdeath);
  }
}
