/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Subtopics;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SubtopicsRecord extends UpdatableRecordImpl<SubtopicsRecord>
    implements Record8<UUID, LocalDateTime, JSONB, String, JSONB, LocalDateTime, UUID, JSONB> {

  private static final long serialVersionUID = 328266159;

  /** Setter for <code>public.subtopics.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.subtopics.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.subtopics.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.subtopics.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.subtopics.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.subtopics.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.subtopics.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.subtopics.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.subtopics.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.subtopics.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.subtopics.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.subtopics.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.subtopics.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(6, value);
  }

  /** Getter for <code>public.subtopics.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(6);
  }

  /** Setter for <code>public.subtopics.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(7, value);
  }

  /** Getter for <code>public.subtopics.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(7);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record8 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row8<UUID, LocalDateTime, JSONB, String, JSONB, LocalDateTime, UUID, JSONB> fieldsRow() {
    return (Row8) super.fieldsRow();
  }

  @Override
  public Row8<UUID, LocalDateTime, JSONB, String, JSONB, LocalDateTime, UUID, JSONB> valuesRow() {
    return (Row8) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Subtopics.SUBTOPICS.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Subtopics.SUBTOPICS.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Subtopics.SUBTOPICS.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Subtopics.SUBTOPICS.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Subtopics.SUBTOPICS.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Subtopics.SUBTOPICS.LAST_MODIFIED;
  }

  @Override
  public Field<UUID> field7() {
    return Subtopics.SUBTOPICS.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field8() {
    return Subtopics.SUBTOPICS.PREVIEW_HINTS;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public UUID component7() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component8() {
    return getPreviewHints();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public UUID value7() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value8() {
    return getPreviewHints();
  }

  @Override
  public SubtopicsRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public SubtopicsRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public SubtopicsRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public SubtopicsRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public SubtopicsRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public SubtopicsRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public SubtopicsRecord value7(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public SubtopicsRecord value8(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public SubtopicsRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      UUID value7,
      JSONB value8) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached SubtopicsRecord */
  public SubtopicsRecord() {
    super(Subtopics.SUBTOPICS);
  }

  /** Create a detached, initialised SubtopicsRecord */
  public SubtopicsRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      UUID previewfileresource,
      JSONB previewHints) {
    super(Subtopics.SUBTOPICS);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, previewfileresource);
    set(7, previewHints);
  }
}
