/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicSubtopics;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SubtopicSubtopicsRecord extends UpdatableRecordImpl<SubtopicSubtopicsRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = -1917612127;

  /** Setter for <code>public.subtopic_subtopics.parent_subtopic_uuid</code>. */
  public void setParentSubtopicUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.subtopic_subtopics.parent_subtopic_uuid</code>. */
  public UUID getParentSubtopicUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.subtopic_subtopics.child_subtopic_uuid</code>. */
  public void setChildSubtopicUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.subtopic_subtopics.child_subtopic_uuid</code>. */
  public UUID getChildSubtopicUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.subtopic_subtopics.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.subtopic_subtopics.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return SubtopicSubtopics.SUBTOPIC_SUBTOPICS.PARENT_SUBTOPIC_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return SubtopicSubtopics.SUBTOPIC_SUBTOPICS.CHILD_SUBTOPIC_UUID;
  }

  @Override
  public Field<Short> field3() {
    return SubtopicSubtopics.SUBTOPIC_SUBTOPICS.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getParentSubtopicUuid();
  }

  @Override
  public UUID component2() {
    return getChildSubtopicUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getParentSubtopicUuid();
  }

  @Override
  public UUID value2() {
    return getChildSubtopicUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public SubtopicSubtopicsRecord value1(UUID value) {
    setParentSubtopicUuid(value);
    return this;
  }

  @Override
  public SubtopicSubtopicsRecord value2(UUID value) {
    setChildSubtopicUuid(value);
    return this;
  }

  @Override
  public SubtopicSubtopicsRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public SubtopicSubtopicsRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached SubtopicSubtopicsRecord */
  public SubtopicSubtopicsRecord() {
    super(SubtopicSubtopics.SUBTOPIC_SUBTOPICS);
  }

  /** Create a detached, initialised SubtopicSubtopicsRecord */
  public SubtopicSubtopicsRecord(UUID parentSubtopicUuid, UUID childSubtopicUuid, Short sortindex) {
    super(SubtopicSubtopics.SUBTOPIC_SUBTOPICS);

    set(0, parentSubtopicUuid);
    set(1, childSubtopicUuid);
    set(2, sortindex);
  }
}
