/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.SubtopicFileresources;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SubtopicFileresourcesRecord extends UpdatableRecordImpl<SubtopicFileresourcesRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = 1759384394;

  /** Setter for <code>public.subtopic_fileresources.subtopic_uuid</code>. */
  public void setSubtopicUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.subtopic_fileresources.subtopic_uuid</code>. */
  public UUID getSubtopicUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.subtopic_fileresources.fileresource_uuid</code>. */
  public void setFileresourceUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.subtopic_fileresources.fileresource_uuid</code>. */
  public UUID getFileresourceUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.subtopic_fileresources.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.subtopic_fileresources.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return SubtopicFileresources.SUBTOPIC_FILERESOURCES.SUBTOPIC_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return SubtopicFileresources.SUBTOPIC_FILERESOURCES.FILERESOURCE_UUID;
  }

  @Override
  public Field<Short> field3() {
    return SubtopicFileresources.SUBTOPIC_FILERESOURCES.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getSubtopicUuid();
  }

  @Override
  public UUID component2() {
    return getFileresourceUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getSubtopicUuid();
  }

  @Override
  public UUID value2() {
    return getFileresourceUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public SubtopicFileresourcesRecord value1(UUID value) {
    setSubtopicUuid(value);
    return this;
  }

  @Override
  public SubtopicFileresourcesRecord value2(UUID value) {
    setFileresourceUuid(value);
    return this;
  }

  @Override
  public SubtopicFileresourcesRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public SubtopicFileresourcesRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached SubtopicFileresourcesRecord */
  public SubtopicFileresourcesRecord() {
    super(SubtopicFileresources.SUBTOPIC_FILERESOURCES);
  }

  /** Create a detached, initialised SubtopicFileresourcesRecord */
  public SubtopicFileresourcesRecord(UUID subtopicUuid, UUID fileresourceUuid, Short sortindex) {
    super(SubtopicFileresources.SUBTOPIC_FILERESOURCES);

    set(0, subtopicUuid);
    set(1, fileresourceUuid);
    set(2, sortindex);
  }
}
