/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.Websites;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WebsitesRecord extends UpdatableRecordImpl<WebsitesRecord>
    implements Record13<
        UUID,
        LocalDateTime,
        JSONB,
        String,
        JSONB,
        LocalDateTime,
        String,
        String,
        LocalDate,
        Integer,
        UUID,
        JSONB,
        JSONB> {

  private static final long serialVersionUID = -211742360;

  /** Setter for <code>public.websites.uuid</code>. */
  public void setUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.websites.uuid</code>. */
  public UUID getUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.websites.created</code>. */
  public void setCreated(LocalDateTime value) {
    set(1, value);
  }

  /** Getter for <code>public.websites.created</code>. */
  public LocalDateTime getCreated() {
    return (LocalDateTime) get(1);
  }

  /** Setter for <code>public.websites.description</code>. */
  public void setDescription(JSONB value) {
    set(2, value);
  }

  /** Getter for <code>public.websites.description</code>. */
  public JSONB getDescription() {
    return (JSONB) get(2);
  }

  /** Setter for <code>public.websites.identifiable_type</code>. */
  public void setIdentifiableType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.websites.identifiable_type</code>. */
  public String getIdentifiableType() {
    return (String) get(3);
  }

  /** Setter for <code>public.websites.label</code>. */
  public void setLabel(JSONB value) {
    set(4, value);
  }

  /** Getter for <code>public.websites.label</code>. */
  public JSONB getLabel() {
    return (JSONB) get(4);
  }

  /** Setter for <code>public.websites.last_modified</code>. */
  public void setLastModified(LocalDateTime value) {
    set(5, value);
  }

  /** Getter for <code>public.websites.last_modified</code>. */
  public LocalDateTime getLastModified() {
    return (LocalDateTime) get(5);
  }

  /** Setter for <code>public.websites.entity_type</code>. */
  public void setEntityType(String value) {
    set(6, value);
  }

  /** Getter for <code>public.websites.entity_type</code>. */
  public String getEntityType() {
    return (String) get(6);
  }

  /** Setter for <code>public.websites.url</code>. */
  public void setUrl(String value) {
    set(7, value);
  }

  /** Getter for <code>public.websites.url</code>. */
  public String getUrl() {
    return (String) get(7);
  }

  /** Setter for <code>public.websites.registration_date</code>. */
  public void setRegistrationDate(LocalDate value) {
    set(8, value);
  }

  /** Getter for <code>public.websites.registration_date</code>. */
  public LocalDate getRegistrationDate() {
    return (LocalDate) get(8);
  }

  /** Setter for <code>public.websites.refid</code>. */
  public void setRefid(Integer value) {
    set(9, value);
  }

  /** Getter for <code>public.websites.refid</code>. */
  public Integer getRefid() {
    return (Integer) get(9);
  }

  /** Setter for <code>public.websites.previewfileresource</code>. */
  public void setPreviewfileresource(UUID value) {
    set(10, value);
  }

  /** Getter for <code>public.websites.previewfileresource</code>. */
  public UUID getPreviewfileresource() {
    return (UUID) get(10);
  }

  /** Setter for <code>public.websites.preview_hints</code>. */
  public void setPreviewHints(JSONB value) {
    set(11, value);
  }

  /** Getter for <code>public.websites.preview_hints</code>. */
  public JSONB getPreviewHints() {
    return (JSONB) get(11);
  }

  /** Setter for <code>public.websites.custom_attrs</code>. */
  public void setCustomAttrs(JSONB value) {
    set(12, value);
  }

  /** Getter for <code>public.websites.custom_attrs</code>. */
  public JSONB getCustomAttrs() {
    return (JSONB) get(12);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record1<UUID> key() {
    return (Record1) super.key();
  }

  // -------------------------------------------------------------------------
  // Record13 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          LocalDate,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row13) super.fieldsRow();
  }

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          LocalDate,
          Integer,
          UUID,
          JSONB,
          JSONB>
      valuesRow() {
    return (Row13) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return Websites.WEBSITES.UUID;
  }

  @Override
  public Field<LocalDateTime> field2() {
    return Websites.WEBSITES.CREATED;
  }

  @Override
  public Field<JSONB> field3() {
    return Websites.WEBSITES.DESCRIPTION;
  }

  @Override
  public Field<String> field4() {
    return Websites.WEBSITES.IDENTIFIABLE_TYPE;
  }

  @Override
  public Field<JSONB> field5() {
    return Websites.WEBSITES.LABEL;
  }

  @Override
  public Field<LocalDateTime> field6() {
    return Websites.WEBSITES.LAST_MODIFIED;
  }

  @Override
  public Field<String> field7() {
    return Websites.WEBSITES.ENTITY_TYPE;
  }

  @Override
  public Field<String> field8() {
    return Websites.WEBSITES.URL;
  }

  @Override
  public Field<LocalDate> field9() {
    return Websites.WEBSITES.REGISTRATION_DATE;
  }

  @Override
  public Field<Integer> field10() {
    return Websites.WEBSITES.REFID;
  }

  @Override
  public Field<UUID> field11() {
    return Websites.WEBSITES.PREVIEWFILERESOURCE;
  }

  @Override
  public Field<JSONB> field12() {
    return Websites.WEBSITES.PREVIEW_HINTS;
  }

  @Override
  public Field<JSONB> field13() {
    return Websites.WEBSITES.CUSTOM_ATTRS;
  }

  @Override
  public UUID component1() {
    return getUuid();
  }

  @Override
  public LocalDateTime component2() {
    return getCreated();
  }

  @Override
  public JSONB component3() {
    return getDescription();
  }

  @Override
  public String component4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB component5() {
    return getLabel();
  }

  @Override
  public LocalDateTime component6() {
    return getLastModified();
  }

  @Override
  public String component7() {
    return getEntityType();
  }

  @Override
  public String component8() {
    return getUrl();
  }

  @Override
  public LocalDate component9() {
    return getRegistrationDate();
  }

  @Override
  public Integer component10() {
    return getRefid();
  }

  @Override
  public UUID component11() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB component12() {
    return getPreviewHints();
  }

  @Override
  public JSONB component13() {
    return getCustomAttrs();
  }

  @Override
  public UUID value1() {
    return getUuid();
  }

  @Override
  public LocalDateTime value2() {
    return getCreated();
  }

  @Override
  public JSONB value3() {
    return getDescription();
  }

  @Override
  public String value4() {
    return getIdentifiableType();
  }

  @Override
  public JSONB value5() {
    return getLabel();
  }

  @Override
  public LocalDateTime value6() {
    return getLastModified();
  }

  @Override
  public String value7() {
    return getEntityType();
  }

  @Override
  public String value8() {
    return getUrl();
  }

  @Override
  public LocalDate value9() {
    return getRegistrationDate();
  }

  @Override
  public Integer value10() {
    return getRefid();
  }

  @Override
  public UUID value11() {
    return getPreviewfileresource();
  }

  @Override
  public JSONB value12() {
    return getPreviewHints();
  }

  @Override
  public JSONB value13() {
    return getCustomAttrs();
  }

  @Override
  public WebsitesRecord value1(UUID value) {
    setUuid(value);
    return this;
  }

  @Override
  public WebsitesRecord value2(LocalDateTime value) {
    setCreated(value);
    return this;
  }

  @Override
  public WebsitesRecord value3(JSONB value) {
    setDescription(value);
    return this;
  }

  @Override
  public WebsitesRecord value4(String value) {
    setIdentifiableType(value);
    return this;
  }

  @Override
  public WebsitesRecord value5(JSONB value) {
    setLabel(value);
    return this;
  }

  @Override
  public WebsitesRecord value6(LocalDateTime value) {
    setLastModified(value);
    return this;
  }

  @Override
  public WebsitesRecord value7(String value) {
    setEntityType(value);
    return this;
  }

  @Override
  public WebsitesRecord value8(String value) {
    setUrl(value);
    return this;
  }

  @Override
  public WebsitesRecord value9(LocalDate value) {
    setRegistrationDate(value);
    return this;
  }

  @Override
  public WebsitesRecord value10(Integer value) {
    setRefid(value);
    return this;
  }

  @Override
  public WebsitesRecord value11(UUID value) {
    setPreviewfileresource(value);
    return this;
  }

  @Override
  public WebsitesRecord value12(JSONB value) {
    setPreviewHints(value);
    return this;
  }

  @Override
  public WebsitesRecord value13(JSONB value) {
    setCustomAttrs(value);
    return this;
  }

  @Override
  public WebsitesRecord values(
      UUID value1,
      LocalDateTime value2,
      JSONB value3,
      String value4,
      JSONB value5,
      LocalDateTime value6,
      String value7,
      String value8,
      LocalDate value9,
      Integer value10,
      UUID value11,
      JSONB value12,
      JSONB value13) {
    value1(value1);
    value2(value2);
    value3(value3);
    value4(value4);
    value5(value5);
    value6(value6);
    value7(value7);
    value8(value8);
    value9(value9);
    value10(value10);
    value11(value11);
    value12(value12);
    value13(value13);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached WebsitesRecord */
  public WebsitesRecord() {
    super(Websites.WEBSITES);
  }

  /** Create a detached, initialised WebsitesRecord */
  public WebsitesRecord(
      UUID uuid,
      LocalDateTime created,
      JSONB description,
      String identifiableType,
      JSONB label,
      LocalDateTime lastModified,
      String entityType,
      String url,
      LocalDate registrationDate,
      Integer refid,
      UUID previewfileresource,
      JSONB previewHints,
      JSONB customAttrs) {
    super(Websites.WEBSITES);

    set(0, uuid);
    set(1, created);
    set(2, description);
    set(3, identifiableType);
    set(4, label);
    set(5, lastModified);
    set(6, entityType);
    set(7, url);
    set(8, registrationDate);
    set(9, refid);
    set(10, previewfileresource);
    set(11, previewHints);
    set(12, customAttrs);
  }
}
