/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WebsiteWebpages;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WebsiteWebpagesRecord extends UpdatableRecordImpl<WebsiteWebpagesRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = -1419100427;

  /** Setter for <code>public.website_webpages.website_uuid</code>. */
  public void setWebsiteUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.website_webpages.website_uuid</code>. */
  public UUID getWebsiteUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.website_webpages.webpage_uuid</code>. */
  public void setWebpageUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.website_webpages.webpage_uuid</code>. */
  public UUID getWebpageUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.website_webpages.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.website_webpages.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return WebsiteWebpages.WEBSITE_WEBPAGES.WEBSITE_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return WebsiteWebpages.WEBSITE_WEBPAGES.WEBPAGE_UUID;
  }

  @Override
  public Field<Short> field3() {
    return WebsiteWebpages.WEBSITE_WEBPAGES.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getWebsiteUuid();
  }

  @Override
  public UUID component2() {
    return getWebpageUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getWebsiteUuid();
  }

  @Override
  public UUID value2() {
    return getWebpageUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public WebsiteWebpagesRecord value1(UUID value) {
    setWebsiteUuid(value);
    return this;
  }

  @Override
  public WebsiteWebpagesRecord value2(UUID value) {
    setWebpageUuid(value);
    return this;
  }

  @Override
  public WebsiteWebpagesRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public WebsiteWebpagesRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached WebsiteWebpagesRecord */
  public WebsiteWebpagesRecord() {
    super(WebsiteWebpages.WEBSITE_WEBPAGES);
  }

  /** Create a detached, initialised WebsiteWebpagesRecord */
  public WebsiteWebpagesRecord(UUID websiteUuid, UUID webpageUuid, Short sortindex) {
    super(WebsiteWebpages.WEBSITE_WEBPAGES);

    set(0, websiteUuid);
    set(1, webpageUuid);
    set(2, sortindex);
  }
}
