/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.WorkCreators;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WorkCreatorsRecord extends UpdatableRecordImpl<WorkCreatorsRecord>
    implements Record3<UUID, UUID, Short> {

  private static final long serialVersionUID = -782684212;

  /** Setter for <code>public.work_creators.work_uuid</code>. */
  public void setWorkUuid(UUID value) {
    set(0, value);
  }

  /** Getter for <code>public.work_creators.work_uuid</code>. */
  public UUID getWorkUuid() {
    return (UUID) get(0);
  }

  /** Setter for <code>public.work_creators.agent_uuid</code>. */
  public void setAgentUuid(UUID value) {
    set(1, value);
  }

  /** Getter for <code>public.work_creators.agent_uuid</code>. */
  public UUID getAgentUuid() {
    return (UUID) get(1);
  }

  /** Setter for <code>public.work_creators.sortindex</code>. */
  public void setSortindex(Short value) {
    set(2, value);
  }

  /** Getter for <code>public.work_creators.sortindex</code>. */
  public Short getSortindex() {
    return (Short) get(2);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<UUID, UUID> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Record3 type implementation
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }

  @Override
  public Row3<UUID, UUID, Short> valuesRow() {
    return (Row3) super.valuesRow();
  }

  @Override
  public Field<UUID> field1() {
    return WorkCreators.WORK_CREATORS.WORK_UUID;
  }

  @Override
  public Field<UUID> field2() {
    return WorkCreators.WORK_CREATORS.AGENT_UUID;
  }

  @Override
  public Field<Short> field3() {
    return WorkCreators.WORK_CREATORS.SORTINDEX;
  }

  @Override
  public UUID component1() {
    return getWorkUuid();
  }

  @Override
  public UUID component2() {
    return getAgentUuid();
  }

  @Override
  public Short component3() {
    return getSortindex();
  }

  @Override
  public UUID value1() {
    return getWorkUuid();
  }

  @Override
  public UUID value2() {
    return getAgentUuid();
  }

  @Override
  public Short value3() {
    return getSortindex();
  }

  @Override
  public WorkCreatorsRecord value1(UUID value) {
    setWorkUuid(value);
    return this;
  }

  @Override
  public WorkCreatorsRecord value2(UUID value) {
    setAgentUuid(value);
    return this;
  }

  @Override
  public WorkCreatorsRecord value3(Short value) {
    setSortindex(value);
    return this;
  }

  @Override
  public WorkCreatorsRecord values(UUID value1, UUID value2, Short value3) {
    value1(value1);
    value2(value2);
    value3(value3);
    return this;
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached WorkCreatorsRecord */
  public WorkCreatorsRecord() {
    super(WorkCreators.WORK_CREATORS);
  }

  /** Create a detached, initialised WorkCreatorsRecord */
  public WorkCreatorsRecord(UUID workUuid, UUID agentUuid, Short sortindex) {
    super(WorkCreators.WORK_CREATORS);

    set(0, workUuid);
    set(1, agentUuid);
    set(2, sortindex);
  }
}
