/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.CorporatebodiesRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Corporatebodies extends TableImpl<CorporatebodiesRecord> {

  private static final long serialVersionUID = 722827474;

  /** The reference instance of <code>public.corporatebodies</code> */
  public static final Corporatebodies CORPORATEBODIES = new Corporatebodies();

  /** The class holding records for this type */
  @Override
  public Class<CorporatebodiesRecord> getRecordType() {
    return CorporatebodiesRecord.class;
  }

  /** The column <code>public.corporatebodies.uuid</code>. */
  public final TableField<CorporatebodiesRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.corporatebodies.created</code>. */
  public final TableField<CorporatebodiesRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.corporatebodies.description</code>. */
  public final TableField<CorporatebodiesRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.corporatebodies.identifiable_type</code>. */
  public final TableField<CorporatebodiesRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.corporatebodies.label</code>. */
  public final TableField<CorporatebodiesRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.corporatebodies.last_modified</code>. */
  public final TableField<CorporatebodiesRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.corporatebodies.entity_type</code>. */
  public final TableField<CorporatebodiesRecord, String> ENTITY_TYPE =
      createField(
          DSL.name("entity_type"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.corporatebodies.id</code>. */
  public final TableField<CorporatebodiesRecord, Integer> ID =
      createField(
          DSL.name("id"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('corporations_id_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.corporatebodies.text</code>. */
  public final TableField<CorporatebodiesRecord, JSONB> TEXT =
      createField(DSL.name("text"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.corporatebodies.homepage_url</code>. */
  public final TableField<CorporatebodiesRecord, String> HOMEPAGE_URL =
      createField(DSL.name("homepage_url"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

  /** The column <code>public.corporatebodies.refid</code>. */
  public final TableField<CorporatebodiesRecord, Integer> REFID =
      createField(
          DSL.name("refid"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('entities_refid_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.corporatebodies.previewfileresource</code>. */
  public final TableField<CorporatebodiesRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.corporatebodies.preview_hints</code>. */
  public final TableField<CorporatebodiesRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.corporatebodies.custom_attrs</code>. */
  public final TableField<CorporatebodiesRecord, JSONB> CUSTOM_ATTRS =
      createField(DSL.name("custom_attrs"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** Create a <code>public.corporatebodies</code> table reference */
  public Corporatebodies() {
    this(DSL.name("corporatebodies"), null);
  }

  /** Create an aliased <code>public.corporatebodies</code> table reference */
  public Corporatebodies(String alias) {
    this(DSL.name(alias), CORPORATEBODIES);
  }

  /** Create an aliased <code>public.corporatebodies</code> table reference */
  public Corporatebodies(Name alias) {
    this(alias, CORPORATEBODIES);
  }

  private Corporatebodies(Name alias, Table<CorporatebodiesRecord> aliased) {
    this(alias, aliased, null);
  }

  private Corporatebodies(Name alias, Table<CorporatebodiesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Corporatebodies(
      Table<O> child, ForeignKey<O, CorporatebodiesRecord> key) {
    super(child, key, CORPORATEBODIES);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public Identity<CorporatebodiesRecord, Integer> getIdentity() {
    return Keys.IDENTITY_CORPORATEBODIES;
  }

  @Override
  public UniqueKey<CorporatebodiesRecord> getPrimaryKey() {
    return Keys.CORPORATIONS_PKEY;
  }

  @Override
  public List<UniqueKey<CorporatebodiesRecord>> getKeys() {
    return Arrays.<UniqueKey<CorporatebodiesRecord>>asList(
        Keys.CORPORATIONS_UUID_KEY, Keys.CORPORATIONS_PKEY);
  }

  @Override
  public Corporatebodies as(String alias) {
    return new Corporatebodies(DSL.name(alias), this);
  }

  @Override
  public Corporatebodies as(Name alias) {
    return new Corporatebodies(alias, this);
  }

  /** Rename this table */
  @Override
  public Corporatebodies rename(String name) {
    return new Corporatebodies(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Corporatebodies rename(Name name) {
    return new Corporatebodies(name, null);
  }

  // -------------------------------------------------------------------------
  // Row14 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          JSONB,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row14) super.fieldsRow();
  }
}
