/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.EntitiesRecord;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Entities extends TableImpl<EntitiesRecord> {

  private static final long serialVersionUID = -360402391;

  /** The reference instance of <code>public.entities</code> */
  public static final Entities ENTITIES = new Entities();

  /** The class holding records for this type */
  @Override
  public Class<EntitiesRecord> getRecordType() {
    return EntitiesRecord.class;
  }

  /** The column <code>public.entities.uuid</code>. */
  public final TableField<EntitiesRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.entities.created</code>. */
  public final TableField<EntitiesRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.entities.description</code>. */
  public final TableField<EntitiesRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.entities.identifiable_type</code>. */
  public final TableField<EntitiesRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.entities.label</code>. */
  public final TableField<EntitiesRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.entities.last_modified</code>. */
  public final TableField<EntitiesRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.entities.entity_type</code>. */
  public final TableField<EntitiesRecord, String> ENTITY_TYPE =
      createField(
          DSL.name("entity_type"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.entities.refid</code>. */
  public final TableField<EntitiesRecord, Integer> REFID =
      createField(
          DSL.name("refid"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('entities_refid_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.entities.previewfileresource</code>. */
  public final TableField<EntitiesRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.entities.preview_hints</code>. */
  public final TableField<EntitiesRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.entities.custom_attrs</code>. */
  public final TableField<EntitiesRecord, JSONB> CUSTOM_ATTRS =
      createField(DSL.name("custom_attrs"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** Create a <code>public.entities</code> table reference */
  public Entities() {
    this(DSL.name("entities"), null);
  }

  /** Create an aliased <code>public.entities</code> table reference */
  public Entities(String alias) {
    this(DSL.name(alias), ENTITIES);
  }

  /** Create an aliased <code>public.entities</code> table reference */
  public Entities(Name alias) {
    this(alias, ENTITIES);
  }

  private Entities(Name alias, Table<EntitiesRecord> aliased) {
    this(alias, aliased, null);
  }

  private Entities(Name alias, Table<EntitiesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Entities(Table<O> child, ForeignKey<O, EntitiesRecord> key) {
    super(child, key, ENTITIES);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public Identity<EntitiesRecord, Integer> getIdentity() {
    return Keys.IDENTITY_ENTITIES;
  }

  @Override
  public Entities as(String alias) {
    return new Entities(DSL.name(alias), this);
  }

  @Override
  public Entities as(Name alias) {
    return new Entities(alias, this);
  }

  /** Rename this table */
  @Override
  public Entities rename(String name) {
    return new Entities(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Entities rename(Name name) {
    return new Entities(name, null);
  }

  // -------------------------------------------------------------------------
  // Row11 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row11<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row11) super.fieldsRow();
  }
}
