/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FileresourcesTextRecord;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FileresourcesText extends TableImpl<FileresourcesTextRecord> {

  private static final long serialVersionUID = 169131665;

  /** The reference instance of <code>public.fileresources_text</code> */
  public static final FileresourcesText FILERESOURCES_TEXT = new FileresourcesText();

  /** The class holding records for this type */
  @Override
  public Class<FileresourcesTextRecord> getRecordType() {
    return FileresourcesTextRecord.class;
  }

  /** The column <code>public.fileresources_text.uuid</code>. */
  public final TableField<FileresourcesTextRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.fileresources_text.created</code>. */
  public final TableField<FileresourcesTextRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.fileresources_text.description</code>. */
  public final TableField<FileresourcesTextRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.fileresources_text.identifiable_type</code>. */
  public final TableField<FileresourcesTextRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.fileresources_text.label</code>. */
  public final TableField<FileresourcesTextRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.fileresources_text.last_modified</code>. */
  public final TableField<FileresourcesTextRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.fileresources_text.filename</code>. */
  public final TableField<FileresourcesTextRecord, String> FILENAME =
      createField(
          DSL.name("filename"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.fileresources_text.mimetype</code>. */
  public final TableField<FileresourcesTextRecord, String> MIMETYPE =
      createField(
          DSL.name("mimetype"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.fileresources_text.size_in_bytes</code>. */
  public final TableField<FileresourcesTextRecord, Long> SIZE_IN_BYTES =
      createField(
          DSL.name("size_in_bytes"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>public.fileresources_text.uri</code>. */
  public final TableField<FileresourcesTextRecord, String> URI =
      createField(DSL.name("uri"), org.jooq.impl.SQLDataType.CLOB, this, "");

  /** The column <code>public.fileresources_text.previewfileresource</code>. */
  public final TableField<FileresourcesTextRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.fileresources_text.preview_hints</code>. */
  public final TableField<FileresourcesTextRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.fileresources_text.http_base_url</code>. */
  public final TableField<FileresourcesTextRecord, String> HTTP_BASE_URL =
      createField(DSL.name("http_base_url"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

  /** Create a <code>public.fileresources_text</code> table reference */
  public FileresourcesText() {
    this(DSL.name("fileresources_text"), null);
  }

  /** Create an aliased <code>public.fileresources_text</code> table reference */
  public FileresourcesText(String alias) {
    this(DSL.name(alias), FILERESOURCES_TEXT);
  }

  /** Create an aliased <code>public.fileresources_text</code> table reference */
  public FileresourcesText(Name alias) {
    this(alias, FILERESOURCES_TEXT);
  }

  private FileresourcesText(Name alias, Table<FileresourcesTextRecord> aliased) {
    this(alias, aliased, null);
  }

  private FileresourcesText(
      Name alias, Table<FileresourcesTextRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> FileresourcesText(
      Table<O> child, ForeignKey<O, FileresourcesTextRecord> key) {
    super(child, key, FILERESOURCES_TEXT);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public FileresourcesText as(String alias) {
    return new FileresourcesText(DSL.name(alias), this);
  }

  @Override
  public FileresourcesText as(Name alias) {
    return new FileresourcesText(alias, this);
  }

  /** Rename this table */
  @Override
  public FileresourcesText rename(String name) {
    return new FileresourcesText(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public FileresourcesText rename(Name name) {
    return new FileresourcesText(name, null);
  }

  // -------------------------------------------------------------------------
  // Row13 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          Long,
          String,
          UUID,
          JSONB,
          String>
      fieldsRow() {
    return (Row13) super.fieldsRow();
  }
}
