/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.FileresourcesApplicationRecord;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class FileresourcesApplication extends TableImpl<FileresourcesApplicationRecord> {

  private static final long serialVersionUID = -1307125042;

  /** The reference instance of <code>public.fileresources_application</code> */
  public static final FileresourcesApplication FILERESOURCES_APPLICATION =
      new FileresourcesApplication();

  /** The class holding records for this type */
  @Override
  public Class<FileresourcesApplicationRecord> getRecordType() {
    return FileresourcesApplicationRecord.class;
  }

  /** The column <code>public.fileresources_application.uuid</code>. */
  public final TableField<FileresourcesApplicationRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.fileresources_application.created</code>. */
  public final TableField<FileresourcesApplicationRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.fileresources_application.description</code>. */
  public final TableField<FileresourcesApplicationRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.fileresources_application.identifiable_type</code>. */
  public final TableField<FileresourcesApplicationRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.fileresources_application.label</code>. */
  public final TableField<FileresourcesApplicationRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.fileresources_application.last_modified</code>. */
  public final TableField<FileresourcesApplicationRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.fileresources_application.filename</code>. */
  public final TableField<FileresourcesApplicationRecord, String> FILENAME =
      createField(
          DSL.name("filename"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.fileresources_application.mimetype</code>. */
  public final TableField<FileresourcesApplicationRecord, String> MIMETYPE =
      createField(
          DSL.name("mimetype"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.fileresources_application.size_in_bytes</code>. */
  public final TableField<FileresourcesApplicationRecord, Long> SIZE_IN_BYTES =
      createField(
          DSL.name("size_in_bytes"), org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

  /** The column <code>public.fileresources_application.uri</code>. */
  public final TableField<FileresourcesApplicationRecord, String> URI =
      createField(DSL.name("uri"), org.jooq.impl.SQLDataType.CLOB, this, "");

  /** The column <code>public.fileresources_application.previewfileresource</code>. */
  public final TableField<FileresourcesApplicationRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.fileresources_application.preview_hints</code>. */
  public final TableField<FileresourcesApplicationRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.fileresources_application.http_base_url</code>. */
  public final TableField<FileresourcesApplicationRecord, String> HTTP_BASE_URL =
      createField(DSL.name("http_base_url"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

  /** Create a <code>public.fileresources_application</code> table reference */
  public FileresourcesApplication() {
    this(DSL.name("fileresources_application"), null);
  }

  /** Create an aliased <code>public.fileresources_application</code> table reference */
  public FileresourcesApplication(String alias) {
    this(DSL.name(alias), FILERESOURCES_APPLICATION);
  }

  /** Create an aliased <code>public.fileresources_application</code> table reference */
  public FileresourcesApplication(Name alias) {
    this(alias, FILERESOURCES_APPLICATION);
  }

  private FileresourcesApplication(Name alias, Table<FileresourcesApplicationRecord> aliased) {
    this(alias, aliased, null);
  }

  private FileresourcesApplication(
      Name alias, Table<FileresourcesApplicationRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> FileresourcesApplication(
      Table<O> child, ForeignKey<O, FileresourcesApplicationRecord> key) {
    super(child, key, FILERESOURCES_APPLICATION);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public FileresourcesApplication as(String alias) {
    return new FileresourcesApplication(DSL.name(alias), this);
  }

  @Override
  public FileresourcesApplication as(Name alias) {
    return new FileresourcesApplication(alias, this);
  }

  /** Rename this table */
  @Override
  public FileresourcesApplication rename(String name) {
    return new FileresourcesApplication(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public FileresourcesApplication rename(Name name) {
    return new FileresourcesApplication(name, null);
  }

  // -------------------------------------------------------------------------
  // Row13 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          Long,
          String,
          UUID,
          JSONB,
          String>
      fieldsRow() {
    return (Row13) super.fieldsRow();
  }
}
