/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.HumansettlementsRecord;
import java.time.LocalDateTime;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row14;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Humansettlements extends TableImpl<HumansettlementsRecord> {

  private static final long serialVersionUID = 1772948610;

  /** The reference instance of <code>public.humansettlements</code> */
  public static final Humansettlements HUMANSETTLEMENTS = new Humansettlements();

  /** The class holding records for this type */
  @Override
  public Class<HumansettlementsRecord> getRecordType() {
    return HumansettlementsRecord.class;
  }

  /** The column <code>public.humansettlements.uuid</code>. */
  public final TableField<HumansettlementsRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.humansettlements.created</code>. */
  public final TableField<HumansettlementsRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.humansettlements.description</code>. */
  public final TableField<HumansettlementsRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.humansettlements.identifiable_type</code>. */
  public final TableField<HumansettlementsRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.humansettlements.label</code>. */
  public final TableField<HumansettlementsRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.humansettlements.last_modified</code>. */
  public final TableField<HumansettlementsRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.humansettlements.entity_type</code>. */
  public final TableField<HumansettlementsRecord, String> ENTITY_TYPE =
      createField(
          DSL.name("entity_type"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.humansettlements.refid</code>. */
  public final TableField<HumansettlementsRecord, Integer> REFID =
      createField(
          DSL.name("refid"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('entities_refid_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.humansettlements.previewfileresource</code>. */
  public final TableField<HumansettlementsRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.humansettlements.preview_hints</code>. */
  public final TableField<HumansettlementsRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.humansettlements.custom_attrs</code>. */
  public final TableField<HumansettlementsRecord, JSONB> CUSTOM_ATTRS =
      createField(DSL.name("custom_attrs"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.humansettlements.geolocation_type</code>. */
  public final TableField<HumansettlementsRecord, String> GEOLOCATION_TYPE =
      createField(DSL.name("geolocation_type"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

  /** The column <code>public.humansettlements.coordinate_location</code>. */
  public final TableField<HumansettlementsRecord, JSONB> COORDINATE_LOCATION =
      createField(DSL.name("coordinate_location"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.humansettlements.settlement_type</code>. */
  public final TableField<HumansettlementsRecord, String> SETTLEMENT_TYPE =
      createField(DSL.name("settlement_type"), org.jooq.impl.SQLDataType.VARCHAR, this, "");

  /** Create a <code>public.humansettlements</code> table reference */
  public Humansettlements() {
    this(DSL.name("humansettlements"), null);
  }

  /** Create an aliased <code>public.humansettlements</code> table reference */
  public Humansettlements(String alias) {
    this(DSL.name(alias), HUMANSETTLEMENTS);
  }

  /** Create an aliased <code>public.humansettlements</code> table reference */
  public Humansettlements(Name alias) {
    this(alias, HUMANSETTLEMENTS);
  }

  private Humansettlements(Name alias, Table<HumansettlementsRecord> aliased) {
    this(alias, aliased, null);
  }

  private Humansettlements(
      Name alias, Table<HumansettlementsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Humansettlements(
      Table<O> child, ForeignKey<O, HumansettlementsRecord> key) {
    super(child, key, HUMANSETTLEMENTS);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public Identity<HumansettlementsRecord, Integer> getIdentity() {
    return Keys.IDENTITY_HUMANSETTLEMENTS;
  }

  @Override
  public Humansettlements as(String alias) {
    return new Humansettlements(DSL.name(alias), this);
  }

  @Override
  public Humansettlements as(Name alias) {
    return new Humansettlements(alias, this);
  }

  /** Rename this table */
  @Override
  public Humansettlements rename(String name) {
    return new Humansettlements(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Humansettlements rename(Name name) {
    return new Humansettlements(name, null);
  }

  // -------------------------------------------------------------------------
  // Row14 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row14<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB,
          String,
          JSONB,
          String>
      fieldsRow() {
    return (Row14) super.fieldsRow();
  }
}
