/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.IdentifiablesRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row8;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Identifiables extends TableImpl<IdentifiablesRecord> {

  private static final long serialVersionUID = -1173495759;

  /** The reference instance of <code>public.identifiables</code> */
  public static final Identifiables IDENTIFIABLES = new Identifiables();

  /** The class holding records for this type */
  @Override
  public Class<IdentifiablesRecord> getRecordType() {
    return IdentifiablesRecord.class;
  }

  /** The column <code>public.identifiables.uuid</code>. */
  public final TableField<IdentifiablesRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.identifiables.created</code>. */
  public final TableField<IdentifiablesRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.identifiables.description</code>. */
  public final TableField<IdentifiablesRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.identifiables.identifiable_type</code>. */
  public final TableField<IdentifiablesRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.identifiables.label</code>. */
  public final TableField<IdentifiablesRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.identifiables.last_modified</code>. */
  public final TableField<IdentifiablesRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.identifiables.previewfileresource</code>. */
  public final TableField<IdentifiablesRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.identifiables.preview_hints</code>. */
  public final TableField<IdentifiablesRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** Create a <code>public.identifiables</code> table reference */
  public Identifiables() {
    this(DSL.name("identifiables"), null);
  }

  /** Create an aliased <code>public.identifiables</code> table reference */
  public Identifiables(String alias) {
    this(DSL.name(alias), IDENTIFIABLES);
  }

  /** Create an aliased <code>public.identifiables</code> table reference */
  public Identifiables(Name alias) {
    this(alias, IDENTIFIABLES);
  }

  private Identifiables(Name alias, Table<IdentifiablesRecord> aliased) {
    this(alias, aliased, null);
  }

  private Identifiables(Name alias, Table<IdentifiablesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Identifiables(Table<O> child, ForeignKey<O, IdentifiablesRecord> key) {
    super(child, key, IDENTIFIABLES);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public UniqueKey<IdentifiablesRecord> getPrimaryKey() {
    return Keys.NEW_IDENTIFIABLES_PKEY;
  }

  @Override
  public List<UniqueKey<IdentifiablesRecord>> getKeys() {
    return Arrays.<UniqueKey<IdentifiablesRecord>>asList(Keys.NEW_IDENTIFIABLES_PKEY);
  }

  @Override
  public Identifiables as(String alias) {
    return new Identifiables(DSL.name(alias), this);
  }

  @Override
  public Identifiables as(Name alias) {
    return new Identifiables(alias, this);
  }

  /** Rename this table */
  @Override
  public Identifiables rename(String name) {
    return new Identifiables(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Identifiables rename(Name name) {
    return new Identifiables(name, null);
  }

  // -------------------------------------------------------------------------
  // Row8 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row8<UUID, LocalDateTime, JSONB, String, JSONB, LocalDateTime, UUID, JSONB> fieldsRow() {
    return (Row8) super.fieldsRow();
  }
}
