/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ItemWorksRecord;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class ItemWorks extends TableImpl<ItemWorksRecord> {

  private static final long serialVersionUID = 612981520;

  /** The reference instance of <code>public.item_works</code> */
  public static final ItemWorks ITEM_WORKS = new ItemWorks();

  /** The class holding records for this type */
  @Override
  public Class<ItemWorksRecord> getRecordType() {
    return ItemWorksRecord.class;
  }

  /** The column <code>public.item_works.item_uuid</code>. */
  public final TableField<ItemWorksRecord, UUID> ITEM_UUID =
      createField(DSL.name("item_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.item_works.work_uuid</code>. */
  public final TableField<ItemWorksRecord, UUID> WORK_UUID =
      createField(DSL.name("work_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.item_works.sortindex</code>. */
  public final TableField<ItemWorksRecord, Short> SORTINDEX =
      createField(DSL.name("sortindex"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

  /** Create a <code>public.item_works</code> table reference */
  public ItemWorks() {
    this(DSL.name("item_works"), null);
  }

  /** Create an aliased <code>public.item_works</code> table reference */
  public ItemWorks(String alias) {
    this(DSL.name(alias), ITEM_WORKS);
  }

  /** Create an aliased <code>public.item_works</code> table reference */
  public ItemWorks(Name alias) {
    this(alias, ITEM_WORKS);
  }

  private ItemWorks(Name alias, Table<ItemWorksRecord> aliased) {
    this(alias, aliased, null);
  }

  private ItemWorks(Name alias, Table<ItemWorksRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> ItemWorks(Table<O> child, ForeignKey<O, ItemWorksRecord> key) {
    super(child, key, ITEM_WORKS);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public UniqueKey<ItemWorksRecord> getPrimaryKey() {
    return Keys.ITEM_WORKS_PKEY;
  }

  @Override
  public List<UniqueKey<ItemWorksRecord>> getKeys() {
    return Arrays.<UniqueKey<ItemWorksRecord>>asList(Keys.ITEM_WORKS_PKEY);
  }

  @Override
  public ItemWorks as(String alias) {
    return new ItemWorks(DSL.name(alias), this);
  }

  @Override
  public ItemWorks as(Name alias) {
    return new ItemWorks(alias, this);
  }

  /** Rename this table */
  @Override
  public ItemWorks rename(String name) {
    return new ItemWorks(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public ItemWorks rename(Name name) {
    return new ItemWorks(name, null);
  }

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }
}
