/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.ProjectsRecord;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row15;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Projects extends TableImpl<ProjectsRecord> {

  private static final long serialVersionUID = 377251002;

  /** The reference instance of <code>public.projects</code> */
  public static final Projects PROJECTS = new Projects();

  /** The class holding records for this type */
  @Override
  public Class<ProjectsRecord> getRecordType() {
    return ProjectsRecord.class;
  }

  /** The column <code>public.projects.uuid</code>. */
  public final TableField<ProjectsRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.projects.created</code>. */
  public final TableField<ProjectsRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.projects.description</code>. */
  public final TableField<ProjectsRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.projects.identifiable_type</code>. */
  public final TableField<ProjectsRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.projects.label</code>. */
  public final TableField<ProjectsRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.projects.last_modified</code>. */
  public final TableField<ProjectsRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.projects.entity_type</code>. */
  public final TableField<ProjectsRecord, String> ENTITY_TYPE =
      createField(
          DSL.name("entity_type"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.projects.id</code>. */
  public final TableField<ProjectsRecord, Integer> ID =
      createField(
          DSL.name("id"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('projects_id_seq'::regclass)", org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.projects.text</code>. */
  public final TableField<ProjectsRecord, JSONB> TEXT =
      createField(DSL.name("text"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.projects.start_date</code>. */
  public final TableField<ProjectsRecord, LocalDate> START_DATE =
      createField(DSL.name("start_date"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

  /** The column <code>public.projects.end_date</code>. */
  public final TableField<ProjectsRecord, LocalDate> END_DATE =
      createField(DSL.name("end_date"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

  /** The column <code>public.projects.refid</code>. */
  public final TableField<ProjectsRecord, Integer> REFID =
      createField(
          DSL.name("refid"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('entities_refid_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.projects.previewfileresource</code>. */
  public final TableField<ProjectsRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.projects.preview_hints</code>. */
  public final TableField<ProjectsRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.projects.custom_attrs</code>. */
  public final TableField<ProjectsRecord, JSONB> CUSTOM_ATTRS =
      createField(DSL.name("custom_attrs"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** Create a <code>public.projects</code> table reference */
  public Projects() {
    this(DSL.name("projects"), null);
  }

  /** Create an aliased <code>public.projects</code> table reference */
  public Projects(String alias) {
    this(DSL.name(alias), PROJECTS);
  }

  /** Create an aliased <code>public.projects</code> table reference */
  public Projects(Name alias) {
    this(alias, PROJECTS);
  }

  private Projects(Name alias, Table<ProjectsRecord> aliased) {
    this(alias, aliased, null);
  }

  private Projects(Name alias, Table<ProjectsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Projects(Table<O> child, ForeignKey<O, ProjectsRecord> key) {
    super(child, key, PROJECTS);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public Identity<ProjectsRecord, Integer> getIdentity() {
    return Keys.IDENTITY_PROJECTS;
  }

  @Override
  public UniqueKey<ProjectsRecord> getPrimaryKey() {
    return Keys.PROJECTS_PKEY;
  }

  @Override
  public List<UniqueKey<ProjectsRecord>> getKeys() {
    return Arrays.<UniqueKey<ProjectsRecord>>asList(Keys.PROJECTS_UUID_KEY, Keys.PROJECTS_PKEY);
  }

  @Override
  public Projects as(String alias) {
    return new Projects(DSL.name(alias), this);
  }

  @Override
  public Projects as(Name alias) {
    return new Projects(alias, this);
  }

  /** Rename this table */
  @Override
  public Projects rename(String name) {
    return new Projects(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Projects rename(Name name) {
    return new Projects(name, null);
  }

  // -------------------------------------------------------------------------
  // Row15 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row15<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          JSONB,
          LocalDate,
          LocalDate,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row15) super.fieldsRow();
  }
}
