/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.RelEntitypartFileresourcesRecord;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class RelEntitypartFileresources extends TableImpl<RelEntitypartFileresourcesRecord> {

  private static final long serialVersionUID = -566164573;

  /** The reference instance of <code>public.rel_entitypart_fileresources</code> */
  public static final RelEntitypartFileresources REL_ENTITYPART_FILERESOURCES =
      new RelEntitypartFileresources();

  /** The class holding records for this type */
  @Override
  public Class<RelEntitypartFileresourcesRecord> getRecordType() {
    return RelEntitypartFileresourcesRecord.class;
  }

  /** The column <code>public.rel_entitypart_fileresources.entitypart_uuid</code>. */
  public final TableField<RelEntitypartFileresourcesRecord, UUID> ENTITYPART_UUID =
      createField(
          DSL.name("entitypart_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.rel_entitypart_fileresources.fileresource_uuid</code>. */
  public final TableField<RelEntitypartFileresourcesRecord, UUID> FILERESOURCE_UUID =
      createField(
          DSL.name("fileresource_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.rel_entitypart_fileresources.sortindex</code>. */
  public final TableField<RelEntitypartFileresourcesRecord, Short> SORTINDEX =
      createField(DSL.name("sortindex"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

  /** Create a <code>public.rel_entitypart_fileresources</code> table reference */
  public RelEntitypartFileresources() {
    this(DSL.name("rel_entitypart_fileresources"), null);
  }

  /** Create an aliased <code>public.rel_entitypart_fileresources</code> table reference */
  public RelEntitypartFileresources(String alias) {
    this(DSL.name(alias), REL_ENTITYPART_FILERESOURCES);
  }

  /** Create an aliased <code>public.rel_entitypart_fileresources</code> table reference */
  public RelEntitypartFileresources(Name alias) {
    this(alias, REL_ENTITYPART_FILERESOURCES);
  }

  private RelEntitypartFileresources(Name alias, Table<RelEntitypartFileresourcesRecord> aliased) {
    this(alias, aliased, null);
  }

  private RelEntitypartFileresources(
      Name alias, Table<RelEntitypartFileresourcesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> RelEntitypartFileresources(
      Table<O> child, ForeignKey<O, RelEntitypartFileresourcesRecord> key) {
    super(child, key, REL_ENTITYPART_FILERESOURCES);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public UniqueKey<RelEntitypartFileresourcesRecord> getPrimaryKey() {
    return Keys.REL_ENTITYPART_FILERESOURCES_PKEY;
  }

  @Override
  public List<UniqueKey<RelEntitypartFileresourcesRecord>> getKeys() {
    return Arrays.<UniqueKey<RelEntitypartFileresourcesRecord>>asList(
        Keys.REL_ENTITYPART_FILERESOURCES_PKEY);
  }

  @Override
  public List<ForeignKey<RelEntitypartFileresourcesRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<RelEntitypartFileresourcesRecord, ?>>asList(
        Keys.REL_ENTITYPART_FILERESOURCES__REL_ENTITYPART_FILERESOURCES_FILERESOURCE_UUID_FKEY);
  }

  public Fileresources fileresources() {
    return new Fileresources(
        this,
        Keys.REL_ENTITYPART_FILERESOURCES__REL_ENTITYPART_FILERESOURCES_FILERESOURCE_UUID_FKEY);
  }

  @Override
  public RelEntitypartFileresources as(String alias) {
    return new RelEntitypartFileresources(DSL.name(alias), this);
  }

  @Override
  public RelEntitypartFileresources as(Name alias) {
    return new RelEntitypartFileresources(alias, this);
  }

  /** Rename this table */
  @Override
  public RelEntitypartFileresources rename(String name) {
    return new RelEntitypartFileresources(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public RelEntitypartFileresources rename(Name name) {
    return new RelEntitypartFileresources(name, null);
  }

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }
}
