/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.SubtopicFileresourcesRecord;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class SubtopicFileresources extends TableImpl<SubtopicFileresourcesRecord> {

  private static final long serialVersionUID = -1083697035;

  /** The reference instance of <code>public.subtopic_fileresources</code> */
  public static final SubtopicFileresources SUBTOPIC_FILERESOURCES = new SubtopicFileresources();

  /** The class holding records for this type */
  @Override
  public Class<SubtopicFileresourcesRecord> getRecordType() {
    return SubtopicFileresourcesRecord.class;
  }

  /** The column <code>public.subtopic_fileresources.subtopic_uuid</code>. */
  public final TableField<SubtopicFileresourcesRecord, UUID> SUBTOPIC_UUID =
      createField(
          DSL.name("subtopic_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.subtopic_fileresources.fileresource_uuid</code>. */
  public final TableField<SubtopicFileresourcesRecord, UUID> FILERESOURCE_UUID =
      createField(
          DSL.name("fileresource_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.subtopic_fileresources.sortindex</code>. */
  public final TableField<SubtopicFileresourcesRecord, Short> SORTINDEX =
      createField(DSL.name("sortindex"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

  /** Create a <code>public.subtopic_fileresources</code> table reference */
  public SubtopicFileresources() {
    this(DSL.name("subtopic_fileresources"), null);
  }

  /** Create an aliased <code>public.subtopic_fileresources</code> table reference */
  public SubtopicFileresources(String alias) {
    this(DSL.name(alias), SUBTOPIC_FILERESOURCES);
  }

  /** Create an aliased <code>public.subtopic_fileresources</code> table reference */
  public SubtopicFileresources(Name alias) {
    this(alias, SUBTOPIC_FILERESOURCES);
  }

  private SubtopicFileresources(Name alias, Table<SubtopicFileresourcesRecord> aliased) {
    this(alias, aliased, null);
  }

  private SubtopicFileresources(
      Name alias, Table<SubtopicFileresourcesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> SubtopicFileresources(
      Table<O> child, ForeignKey<O, SubtopicFileresourcesRecord> key) {
    super(child, key, SUBTOPIC_FILERESOURCES);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public UniqueKey<SubtopicFileresourcesRecord> getPrimaryKey() {
    return Keys.SUBTOPIC_FILERESOURCES_PKEY;
  }

  @Override
  public List<UniqueKey<SubtopicFileresourcesRecord>> getKeys() {
    return Arrays.<UniqueKey<SubtopicFileresourcesRecord>>asList(Keys.SUBTOPIC_FILERESOURCES_PKEY);
  }

  @Override
  public List<ForeignKey<SubtopicFileresourcesRecord, ?>> getReferences() {
    return Arrays.<ForeignKey<SubtopicFileresourcesRecord, ?>>asList(
        Keys.SUBTOPIC_FILERESOURCES__SUBTOPIC_FILERESOURCES_SUBTOPIC_UUID_FKEY);
  }

  public Subtopics subtopics() {
    return new Subtopics(
        this, Keys.SUBTOPIC_FILERESOURCES__SUBTOPIC_FILERESOURCES_SUBTOPIC_UUID_FKEY);
  }

  @Override
  public SubtopicFileresources as(String alias) {
    return new SubtopicFileresources(DSL.name(alias), this);
  }

  @Override
  public SubtopicFileresources as(Name alias) {
    return new SubtopicFileresources(alias, this);
  }

  /** Rename this table */
  @Override
  public SubtopicFileresources rename(String name) {
    return new SubtopicFileresources(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public SubtopicFileresources rename(Name name) {
    return new SubtopicFileresources(name, null);
  }

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }
}
