/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.TopicsRecord;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row11;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Topics extends TableImpl<TopicsRecord> {

  private static final long serialVersionUID = 2121648422;

  /** The reference instance of <code>public.topics</code> */
  public static final Topics TOPICS = new Topics();

  /** The class holding records for this type */
  @Override
  public Class<TopicsRecord> getRecordType() {
    return TopicsRecord.class;
  }

  /** The column <code>public.topics.uuid</code>. */
  public final TableField<TopicsRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.topics.created</code>. */
  public final TableField<TopicsRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.topics.description</code>. */
  public final TableField<TopicsRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.topics.identifiable_type</code>. */
  public final TableField<TopicsRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.topics.label</code>. */
  public final TableField<TopicsRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.topics.last_modified</code>. */
  public final TableField<TopicsRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.topics.entity_type</code>. */
  public final TableField<TopicsRecord, String> ENTITY_TYPE =
      createField(
          DSL.name("entity_type"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.topics.refid</code>. */
  public final TableField<TopicsRecord, Integer> REFID =
      createField(
          DSL.name("refid"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('entities_refid_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.topics.previewfileresource</code>. */
  public final TableField<TopicsRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.topics.preview_hints</code>. */
  public final TableField<TopicsRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.topics.custom_attrs</code>. */
  public final TableField<TopicsRecord, JSONB> CUSTOM_ATTRS =
      createField(DSL.name("custom_attrs"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** Create a <code>public.topics</code> table reference */
  public Topics() {
    this(DSL.name("topics"), null);
  }

  /** Create an aliased <code>public.topics</code> table reference */
  public Topics(String alias) {
    this(DSL.name(alias), TOPICS);
  }

  /** Create an aliased <code>public.topics</code> table reference */
  public Topics(Name alias) {
    this(alias, TOPICS);
  }

  private Topics(Name alias, Table<TopicsRecord> aliased) {
    this(alias, aliased, null);
  }

  private Topics(Name alias, Table<TopicsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Topics(Table<O> child, ForeignKey<O, TopicsRecord> key) {
    super(child, key, TOPICS);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public Identity<TopicsRecord, Integer> getIdentity() {
    return Keys.IDENTITY_TOPICS;
  }

  @Override
  public UniqueKey<TopicsRecord> getPrimaryKey() {
    return Keys.TOPICS_PKEY;
  }

  @Override
  public List<UniqueKey<TopicsRecord>> getKeys() {
    return Arrays.<UniqueKey<TopicsRecord>>asList(Keys.TOPICS_PKEY);
  }

  @Override
  public Topics as(String alias) {
    return new Topics(DSL.name(alias), this);
  }

  @Override
  public Topics as(Name alias) {
    return new Topics(alias, this);
  }

  /** Rename this table */
  @Override
  public Topics rename(String name) {
    return new Topics(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Topics rename(Name name) {
    return new Topics(name, null);
  }

  // -------------------------------------------------------------------------
  // Row11 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row11<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row11) super.fieldsRow();
  }
}
