/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WebsitesRecord;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row13;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Websites extends TableImpl<WebsitesRecord> {

  private static final long serialVersionUID = 1234650181;

  /** The reference instance of <code>public.websites</code> */
  public static final Websites WEBSITES = new Websites();

  /** The class holding records for this type */
  @Override
  public Class<WebsitesRecord> getRecordType() {
    return WebsitesRecord.class;
  }

  /** The column <code>public.websites.uuid</code>. */
  public final TableField<WebsitesRecord, UUID> UUID =
      createField(DSL.name("uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.websites.created</code>. */
  public final TableField<WebsitesRecord, LocalDateTime> CREATED =
      createField(
          DSL.name("created"), org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

  /** The column <code>public.websites.description</code>. */
  public final TableField<WebsitesRecord, JSONB> DESCRIPTION =
      createField(DSL.name("description"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.websites.identifiable_type</code>. */
  public final TableField<WebsitesRecord, String> IDENTIFIABLE_TYPE =
      createField(
          DSL.name("identifiable_type"),
          org.jooq.impl.SQLDataType.VARCHAR.nullable(false),
          this,
          "");

  /** The column <code>public.websites.label</code>. */
  public final TableField<WebsitesRecord, JSONB> LABEL =
      createField(DSL.name("label"), org.jooq.impl.SQLDataType.JSONB.nullable(false), this, "");

  /** The column <code>public.websites.last_modified</code>. */
  public final TableField<WebsitesRecord, LocalDateTime> LAST_MODIFIED =
      createField(
          DSL.name("last_modified"),
          org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false),
          this,
          "");

  /** The column <code>public.websites.entity_type</code>. */
  public final TableField<WebsitesRecord, String> ENTITY_TYPE =
      createField(
          DSL.name("entity_type"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.websites.url</code>. */
  public final TableField<WebsitesRecord, String> URL =
      createField(DSL.name("url"), org.jooq.impl.SQLDataType.VARCHAR.nullable(false), this, "");

  /** The column <code>public.websites.registration_date</code>. */
  public final TableField<WebsitesRecord, LocalDate> REGISTRATION_DATE =
      createField(DSL.name("registration_date"), org.jooq.impl.SQLDataType.LOCALDATE, this, "");

  /** The column <code>public.websites.refid</code>. */
  public final TableField<WebsitesRecord, Integer> REFID =
      createField(
          DSL.name("refid"),
          org.jooq.impl.SQLDataType.INTEGER
              .nullable(false)
              .defaultValue(
                  org.jooq.impl.DSL.field(
                      "nextval('entities_refid_seq'::regclass)",
                      org.jooq.impl.SQLDataType.INTEGER)),
          this,
          "");

  /** The column <code>public.websites.previewfileresource</code>. */
  public final TableField<WebsitesRecord, UUID> PREVIEWFILERESOURCE =
      createField(DSL.name("previewfileresource"), org.jooq.impl.SQLDataType.UUID, this, "");

  /** The column <code>public.websites.preview_hints</code>. */
  public final TableField<WebsitesRecord, JSONB> PREVIEW_HINTS =
      createField(DSL.name("preview_hints"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** The column <code>public.websites.custom_attrs</code>. */
  public final TableField<WebsitesRecord, JSONB> CUSTOM_ATTRS =
      createField(DSL.name("custom_attrs"), org.jooq.impl.SQLDataType.JSONB, this, "");

  /** Create a <code>public.websites</code> table reference */
  public Websites() {
    this(DSL.name("websites"), null);
  }

  /** Create an aliased <code>public.websites</code> table reference */
  public Websites(String alias) {
    this(DSL.name(alias), WEBSITES);
  }

  /** Create an aliased <code>public.websites</code> table reference */
  public Websites(Name alias) {
    this(alias, WEBSITES);
  }

  private Websites(Name alias, Table<WebsitesRecord> aliased) {
    this(alias, aliased, null);
  }

  private Websites(Name alias, Table<WebsitesRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> Websites(Table<O> child, ForeignKey<O, WebsitesRecord> key) {
    super(child, key, WEBSITES);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public Identity<WebsitesRecord, Integer> getIdentity() {
    return Keys.IDENTITY_WEBSITES;
  }

  @Override
  public UniqueKey<WebsitesRecord> getPrimaryKey() {
    return Keys.NEW_WEBSITES_PKEY;
  }

  @Override
  public List<UniqueKey<WebsitesRecord>> getKeys() {
    return Arrays.<UniqueKey<WebsitesRecord>>asList(
        Keys.NEW_WEBSITES_PKEY, Keys.NEW_WEBSITES_URL_KEY);
  }

  @Override
  public Websites as(String alias) {
    return new Websites(DSL.name(alias), this);
  }

  @Override
  public Websites as(Name alias) {
    return new Websites(alias, this);
  }

  /** Rename this table */
  @Override
  public Websites rename(String name) {
    return new Websites(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public Websites rename(Name name) {
    return new Websites(name, null);
  }

  // -------------------------------------------------------------------------
  // Row13 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row13<
          UUID,
          LocalDateTime,
          JSONB,
          String,
          JSONB,
          LocalDateTime,
          String,
          String,
          LocalDate,
          Integer,
          UUID,
          JSONB,
          JSONB>
      fieldsRow() {
    return (Row13) super.fieldsRow();
  }
}
