/*
 * This file is generated by jOOQ.
 */
package de.digitalcollections.cudami.server.backend.impl.jooq.db.tables;

import de.digitalcollections.cudami.server.backend.impl.jooq.db.Keys;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.Public;
import de.digitalcollections.cudami.server.backend.impl.jooq.db.tables.records.WorkCreatorsRecord;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.Row3;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class WorkCreators extends TableImpl<WorkCreatorsRecord> {

  private static final long serialVersionUID = 2079545350;

  /** The reference instance of <code>public.work_creators</code> */
  public static final WorkCreators WORK_CREATORS = new WorkCreators();

  /** The class holding records for this type */
  @Override
  public Class<WorkCreatorsRecord> getRecordType() {
    return WorkCreatorsRecord.class;
  }

  /** The column <code>public.work_creators.work_uuid</code>. */
  public final TableField<WorkCreatorsRecord, UUID> WORK_UUID =
      createField(DSL.name("work_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.work_creators.agent_uuid</code>. */
  public final TableField<WorkCreatorsRecord, UUID> AGENT_UUID =
      createField(DSL.name("agent_uuid"), org.jooq.impl.SQLDataType.UUID.nullable(false), this, "");

  /** The column <code>public.work_creators.sortindex</code>. */
  public final TableField<WorkCreatorsRecord, Short> SORTINDEX =
      createField(DSL.name("sortindex"), org.jooq.impl.SQLDataType.SMALLINT, this, "");

  /** Create a <code>public.work_creators</code> table reference */
  public WorkCreators() {
    this(DSL.name("work_creators"), null);
  }

  /** Create an aliased <code>public.work_creators</code> table reference */
  public WorkCreators(String alias) {
    this(DSL.name(alias), WORK_CREATORS);
  }

  /** Create an aliased <code>public.work_creators</code> table reference */
  public WorkCreators(Name alias) {
    this(alias, WORK_CREATORS);
  }

  private WorkCreators(Name alias, Table<WorkCreatorsRecord> aliased) {
    this(alias, aliased, null);
  }

  private WorkCreators(Name alias, Table<WorkCreatorsRecord> aliased, Field<?>[] parameters) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table());
  }

  public <O extends Record> WorkCreators(Table<O> child, ForeignKey<O, WorkCreatorsRecord> key) {
    super(child, key, WORK_CREATORS);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC;
  }

  @Override
  public UniqueKey<WorkCreatorsRecord> getPrimaryKey() {
    return Keys.WORK_CREATORS_PKEY;
  }

  @Override
  public List<UniqueKey<WorkCreatorsRecord>> getKeys() {
    return Arrays.<UniqueKey<WorkCreatorsRecord>>asList(Keys.WORK_CREATORS_PKEY);
  }

  @Override
  public WorkCreators as(String alias) {
    return new WorkCreators(DSL.name(alias), this);
  }

  @Override
  public WorkCreators as(Name alias) {
    return new WorkCreators(alias, this);
  }

  /** Rename this table */
  @Override
  public WorkCreators rename(String name) {
    return new WorkCreators(DSL.name(name), null);
  }

  /** Rename this table */
  @Override
  public WorkCreators rename(Name name) {
    return new WorkCreators(name, null);
  }

  // -------------------------------------------------------------------------
  // Row3 type methods
  // -------------------------------------------------------------------------

  @Override
  public Row3<UUID, UUID, Short> fieldsRow() {
    return (Row3) super.fieldsRow();
  }
}
